/**
 * StyleCoverage.test.ts — Parametric subdivision coverage tests for style variety
 *
 * Tests that subdivision logic correctly handles the variety of feature patterns
 * generated by different style categories. While the subdivision code is style-agnostic,
 * these tests verify that feature patterns characteristic of each style category
 * trigger appropriate subdivision behavior.
 *
 * Style categories covered:
 * 1. **Dense Regular** (superformula, harmonic, wave_interference): High feature count, regular spacing
 * 2. **Sparse Dramatic** (gothic_arches, art_deco): Few features, large amplitude
 * 3. **Complex Overlapping** (celtic_knot, celtic_triquetra): Features that cross rows
 * 4. **Gradient-based** (spiral, fourier): Gradually varying features
 * 5. **Cellular** (voronoi, hexagonal_hive): Cell-like patterns
 * 6. **Scale Patterns** (dragon_scales, bamboo_segments): Repeating motifs
 * 7. **Low-poly** (low_poly_facet): Intentionally sparse features
 *
 * These tests use CPU mocks to simulate GPU evaluation, verifying that:
 * - Chain detection via UV-proximity works for all pattern types
 * - Long edges trigger subdivision regardless of feature density
 * - Feature chains at various positions (including near-seam) are handled
 *
 * @module StyleCoverage.test
 */

import { describe, it, expect } from 'vitest';
import {
    subdivideLongEdges,
    identifyChainAdjacentVertices,
    type SubdivisionParams,
    type EvaluateMidpointsFn,
    type ChainUV,
} from './MeshSubdivision';

// ─────────────────────────────────────────────────────────────────────
// Test Helpers
// ─────────────────────────────────────────────────────────────────────

/**
 * Generate a grid mesh with specified dimensions.
 * All vertices are grid vertices (no separate chain vertices).
 * 
 * @param numU Number of columns
 * @param numT Number of rows
 * @param spacing Grid spacing in mm
 * @returns Mesh data arrays
 */
function generateGridMesh(numU: number, numT: number, spacing: number = 3) {
    const totalVerts = numU * numT;
    const resultData = new Float32Array(totalVerts * 3);
    const combinedVerts = new Float32Array(totalVerts * 3);

    for (let t = 0; t < numT; t++) {
        for (let u = 0; u < numU; u++) {
            const idx = t * numU + u;
            resultData[idx * 3] = u * spacing;
            resultData[idx * 3 + 1] = 0;
            resultData[idx * 3 + 2] = t * spacing;
            combinedVerts[idx * 3] = u / numU;
            combinedVerts[idx * 3 + 1] = t / (numT - 1);
            combinedVerts[idx * 3 + 2] = 0; // surfaceId
        }
    }

    // Build triangulated grid (2 tris per quad)
    const triIdxs: number[] = [];
    for (let t = 0; t < numT - 1; t++) {
        for (let u = 0; u < numU - 1; u++) {
            const v00 = t * numU + u;
            const v10 = t * numU + u + 1;
            const v01 = (t + 1) * numU + u;
            const v11 = (t + 1) * numU + u + 1;
            triIdxs.push(v00, v10, v01);
            triIdxs.push(v10, v11, v01);
        }
    }
    const combinedIdxs = new Uint32Array(triIdxs);

    return { resultData, combinedVerts, combinedIdxs, totalVerts, numU, numT };
}

/**
 * Apply UV-snapping displacement to vertices at specified chain positions.
 * Simulates the v20.x behavior where grid vertices are UV-snapped to chain positions.
 * 
 * @param resultData 3D position array
 * @param combinedVerts UV array
 * @param numU Grid width
 * @param chains Chain definitions
 * @param displacement How far to move snapped vertices (creates long edges)
 */
function applyChainDisplacement(
    resultData: Float32Array,
    combinedVerts: Float32Array,
    numU: number,
    numT: number,
    chains: ChainUV[],
    displacement: number = 5
): void {
    for (const chain of chains) {
        for (const point of chain.points) {
            const col = Math.round(point.u * numU);
            const row = point.row;
            if (col >= 0 && col < numU && row >= 0 && row < numT) {
                const idx = row * numU + col;
                // UV-snap
                combinedVerts[idx * 3] = point.u;
                // Displace 3D position to create long edges
                resultData[idx * 3] += displacement;
            }
        }
    }
}

/**
 * Create evaluator function that maps UV to 3D positions on a flat plane.
 */
function makeFlatEvaluator(width: number, depth: number): EvaluateMidpointsFn {
    return async (uvBatch: Float32Array): Promise<Float32Array> => {
        const n = uvBatch.length / 3;
        const out = new Float32Array(n * 3);
        for (let i = 0; i < n; i++) {
            out[i * 3] = uvBatch[i * 3] * width;
            out[i * 3 + 1] = 0;
            out[i * 3 + 2] = uvBatch[i * 3 + 1] * depth;
        }
        return out;
    };
}

/**
 * Generate chain patterns for different style categories.
 */
const CHAIN_PATTERNS = {
    /** Dense regular: 8 features evenly spaced (like superformula m=8) */
    denseRegular: (numT: number): ChainUV[] => {
        const chains: ChainUV[] = [];
        for (let i = 0; i < 8; i++) {
            const u = i / 8;
            chains.push({
                points: Array.from({ length: numT - 1 }, (_, row) => ({ u, row }))
            });
        }
        return chains;
    },

    /** Sparse dramatic: 3 large features (like gothic arches) */
    sparseDramatic: (numT: number): ChainUV[] => {
        return [0.15, 0.5, 0.85].map(u => ({
            points: Array.from({ length: numT - 1 }, (_, row) => ({ u, row }))
        }));
    },

    /** Complex overlapping: Features that zigzag across rows (like celtic knot) */
    complexOverlapping: (numT: number): ChainUV[] => {
        const chains: ChainUV[] = [];
        // Create 4 diagonal chains
        for (let strand = 0; strand < 4; strand++) {
            const baseU = 0.2 + strand * 0.2;
            chains.push({
                points: Array.from({ length: numT - 1 }, (_, row) => ({
                    u: (baseU + row * 0.03) % 1.0,
                    row
                }))
            });
        }
        return chains;
    },

    /** Gradient-based: Single spiral feature (like spiral style) */
    gradientBased: (numT: number): ChainUV[] => {
        return [{
            points: Array.from({ length: numT - 1 }, (_, row) => ({
                u: (row * 0.1) % 1.0,
                row
            }))
        }];
    },

    /** Cellular: Hexagonal cell boundaries (like voronoi/hexagonal_hive) */
    cellular: (numT: number): ChainUV[] => {
        const chains: ChainUV[] = [];
        // Create honeycomb-like pattern
        for (let cell = 0; cell < 6; cell++) {
            const u = cell / 6;
            chains.push({
                points: Array.from({ length: Math.floor((numT - 1) / 2) }, (_, i) => ({
                    u: u + (i % 2) * (1 / 12),
                    row: i * 2
                }))
            });
        }
        return chains;
    },

    /** Scale patterns: Regular vertical stripes with gaps (like dragon_scales) */
    scalePatterns: (numT: number): ChainUV[] => {
        const chains: ChainUV[] = [];
        for (let scale = 0; scale < 12; scale++) {
            chains.push({
                points: [
                    { u: scale / 12, row: 0 },
                    { u: scale / 12, row: Math.floor(numT / 2) }
                ]
            });
        }
        return chains;
    },

    /** Near-seam: Features at U ≈ 0 and U ≈ 1 (seam boundary stress test) */
    nearSeam: (numT: number): ChainUV[] => {
        return [
            { points: Array.from({ length: numT - 1 }, (_, row) => ({ u: 0.02, row })) },
            { points: Array.from({ length: numT - 1 }, (_, row) => ({ u: 0.98, row })) }
        ];
    },

    /** Low-poly sparse: Only 1-2 features (like low_poly_facet) */
    lowPolySparse: (numT: number): ChainUV[] => {
        return [{
            points: [{ u: 0.5, row: Math.floor(numT / 2) }]
        }];
    },
};

// ─────────────────────────────────────────────────────────────────────
// Style Pattern Coverage Tests
// ─────────────────────────────────────────────────────────────────────

describe('Style Feature Pattern Coverage', () => {
    // Moderate resolution grid
    const GRID_U = 24;
    const GRID_T = 12;
    const GRID_SPACING = 3; // mm
    const MESH_WIDTH = GRID_U * GRID_SPACING;
    const MESH_DEPTH = GRID_T * GRID_SPACING;

    describe('Dense Regular Patterns (superformula, harmonic, wave_interference)', () => {
        it('detects chain-adjacent vertices for 8 evenly-spaced features', () => {
            const { combinedVerts, totalVerts, numU, numT } = generateGridMesh(GRID_U, GRID_T);
            const chains = CHAIN_PATTERNS.denseRegular(numT);
            const gridSpacing = 1 / numU;

            const chainAdjacent = identifyChainAdjacentVertices(
                combinedVerts, totalVerts, chains, gridSpacing, numT
            );

            // Should detect vertices near each of the 8 chain positions
            expect(chainAdjacent.size).toBeGreaterThan(0);
            // With 8 chains × ~11 rows = ~88 chain-adjacent vertices
            expect(chainAdjacent.size).toBeGreaterThanOrEqual(8);
        });

        it('subdivides long edges in dense feature mesh', async () => {
            const { resultData, combinedVerts, combinedIdxs, totalVerts, numU, numT } = 
                generateGridMesh(GRID_U, GRID_T, GRID_SPACING);
            const chains = CHAIN_PATTERNS.denseRegular(numT);
            
            // Apply displacement to create long edges
            applyChainDisplacement(resultData, combinedVerts, numU, numT, chains, 8);

            const params: SubdivisionParams = {
                combinedIdxs,
                resultData,
                combinedVerts,
                outerIdxCount: combinedIdxs.length,
                outerGridVertexCount: totalVerts, // ALL vertices are grid
                constraintEdgeSet: new Set(),
                outerW: numU,
                outerH: numT,
                chains,
            };

            const result = await subdivideLongEdges(params, makeFlatEvaluator(MESH_WIDTH, MESH_DEPTH));
            
            // Dense features should trigger many subdivisions
            expect(result.splitCount).toBeGreaterThan(0);
        });
    });

    describe('Sparse Dramatic Patterns (gothic_arches, art_deco)', () => {
        it('detects chain-adjacent vertices for 3 dramatic features', () => {
            const { combinedVerts, totalVerts, numU, numT } = generateGridMesh(GRID_U, GRID_T);
            const chains = CHAIN_PATTERNS.sparseDramatic(numT);
            const gridSpacing = 1 / numU;

            const chainAdjacent = identifyChainAdjacentVertices(
                combinedVerts, totalVerts, chains, gridSpacing, numT
            );

            expect(chainAdjacent.size).toBeGreaterThan(0);
        });

        it('subdivides long edges with large displacement (dramatic amplitude)', async () => {
            const { resultData, combinedVerts, combinedIdxs, totalVerts, numU, numT } = 
                generateGridMesh(GRID_U, GRID_T, GRID_SPACING);
            const chains = CHAIN_PATTERNS.sparseDramatic(numT);
            
            // Large displacement for dramatic features
            applyChainDisplacement(resultData, combinedVerts, numU, numT, chains, 15);

            const params: SubdivisionParams = {
                combinedIdxs,
                resultData,
                combinedVerts,
                outerIdxCount: combinedIdxs.length,
                outerGridVertexCount: totalVerts,
                constraintEdgeSet: new Set(),
                outerW: numU,
                outerH: numT,
                chains,
            };

            const result = await subdivideLongEdges(params, makeFlatEvaluator(MESH_WIDTH, MESH_DEPTH));
            
            expect(result.splitCount).toBeGreaterThan(0);
        });
    });

    describe('Complex Overlapping Patterns (celtic_knot, celtic_triquetra)', () => {
        it('detects chain-adjacent vertices for diagonal features', () => {
            const { combinedVerts, totalVerts, numU, numT } = generateGridMesh(GRID_U, GRID_T);
            const chains = CHAIN_PATTERNS.complexOverlapping(numT);
            const gridSpacing = 1 / numU;

            const chainAdjacent = identifyChainAdjacentVertices(
                combinedVerts, totalVerts, chains, gridSpacing, numT
            );

            // Diagonal features should still be detected
            expect(chainAdjacent.size).toBeGreaterThan(0);
        });

        it('subdivides edges with row-varying chain positions', async () => {
            const { resultData, combinedVerts, combinedIdxs, totalVerts, numU, numT } = 
                generateGridMesh(GRID_U, GRID_T, GRID_SPACING);
            const chains = CHAIN_PATTERNS.complexOverlapping(numT);
            
            applyChainDisplacement(resultData, combinedVerts, numU, numT, chains, 6);

            const params: SubdivisionParams = {
                combinedIdxs,
                resultData,
                combinedVerts,
                outerIdxCount: combinedIdxs.length,
                outerGridVertexCount: totalVerts,
                constraintEdgeSet: new Set(),
                outerW: numU,
                outerH: numT,
                chains,
            };

            const result = await subdivideLongEdges(params, makeFlatEvaluator(MESH_WIDTH, MESH_DEPTH));
            
            expect(result.splitCount).toBeGreaterThan(0);
        });
    });

    describe('Gradient-based Patterns (spiral, fourier)', () => {
        it('detects single spiraling feature chain', () => {
            const { combinedVerts, totalVerts, numU, numT } = generateGridMesh(GRID_U, GRID_T);
            const chains = CHAIN_PATTERNS.gradientBased(numT);
            const gridSpacing = 1 / numU;

            const chainAdjacent = identifyChainAdjacentVertices(
                combinedVerts, totalVerts, chains, gridSpacing, numT
            );

            expect(chainAdjacent.size).toBeGreaterThan(0);
        });

        it('subdivides edges along spiraling feature', async () => {
            const { resultData, combinedVerts, combinedIdxs, totalVerts, numU, numT } = 
                generateGridMesh(GRID_U, GRID_T, GRID_SPACING);
            const chains = CHAIN_PATTERNS.gradientBased(numT);
            
            applyChainDisplacement(resultData, combinedVerts, numU, numT, chains, 10);

            const params: SubdivisionParams = {
                combinedIdxs,
                resultData,
                combinedVerts,
                outerIdxCount: combinedIdxs.length,
                outerGridVertexCount: totalVerts,
                constraintEdgeSet: new Set(),
                outerW: numU,
                outerH: numT,
                chains,
            };

            const result = await subdivideLongEdges(params, makeFlatEvaluator(MESH_WIDTH, MESH_DEPTH));
            
            expect(result.splitCount).toBeGreaterThan(0);
        });
    });

    describe('Cellular Patterns (voronoi, hexagonal_hive)', () => {
        it('detects honeycomb-like cell boundaries', () => {
            const { combinedVerts, totalVerts, numU, numT } = generateGridMesh(GRID_U, GRID_T);
            const chains = CHAIN_PATTERNS.cellular(numT);
            const gridSpacing = 1 / numU;

            const chainAdjacent = identifyChainAdjacentVertices(
                combinedVerts, totalVerts, chains, gridSpacing, numT
            );

            expect(chainAdjacent.size).toBeGreaterThan(0);
        });

        it('subdivides edges at cell boundaries', async () => {
            const { resultData, combinedVerts, combinedIdxs, totalVerts, numU, numT } = 
                generateGridMesh(GRID_U, GRID_T, GRID_SPACING);
            const chains = CHAIN_PATTERNS.cellular(numT);
            
            applyChainDisplacement(resultData, combinedVerts, numU, numT, chains, 7);

            const params: SubdivisionParams = {
                combinedIdxs,
                resultData,
                combinedVerts,
                outerIdxCount: combinedIdxs.length,
                outerGridVertexCount: totalVerts,
                constraintEdgeSet: new Set(),
                outerW: numU,
                outerH: numT,
                chains,
            };

            const result = await subdivideLongEdges(params, makeFlatEvaluator(MESH_WIDTH, MESH_DEPTH));
            
            expect(result.splitCount).toBeGreaterThan(0);
        });
    });

    describe('Scale Patterns (dragon_scales, bamboo_segments)', () => {
        it('detects vertical stripe features', () => {
            const { combinedVerts, totalVerts, numU, numT } = generateGridMesh(GRID_U, GRID_T);
            const chains = CHAIN_PATTERNS.scalePatterns(numT);
            const gridSpacing = 1 / numU;

            const chainAdjacent = identifyChainAdjacentVertices(
                combinedVerts, totalVerts, chains, gridSpacing, numT
            );

            expect(chainAdjacent.size).toBeGreaterThan(0);
        });

        it('subdivides edges at scale boundaries', async () => {
            const { resultData, combinedVerts, combinedIdxs, totalVerts, numU, numT } = 
                generateGridMesh(GRID_U, GRID_T, GRID_SPACING);
            const chains = CHAIN_PATTERNS.scalePatterns(numT);
            
            applyChainDisplacement(resultData, combinedVerts, numU, numT, chains, 5);

            const params: SubdivisionParams = {
                combinedIdxs,
                resultData,
                combinedVerts,
                outerIdxCount: combinedIdxs.length,
                outerGridVertexCount: totalVerts,
                constraintEdgeSet: new Set(),
                outerW: numU,
                outerH: numT,
                chains,
            };

            const result = await subdivideLongEdges(params, makeFlatEvaluator(MESH_WIDTH, MESH_DEPTH));
            
            expect(result.splitCount).toBeGreaterThan(0);
        });
    });

    describe('Near-Seam Features (boundary stress test)', () => {
        it('detects features at U ≈ 0 and U ≈ 1', () => {
            const { combinedVerts, totalVerts, numU, numT } = generateGridMesh(GRID_U, GRID_T);
            const chains = CHAIN_PATTERNS.nearSeam(numT);
            const gridSpacing = 1 / numU;

            const chainAdjacent = identifyChainAdjacentVertices(
                combinedVerts, totalVerts, chains, gridSpacing, numT
            );

            // Should detect vertices near both seam edges
            expect(chainAdjacent.size).toBeGreaterThan(0);
        });

        it('subdivides edges near seam boundary', async () => {
            const { resultData, combinedVerts, combinedIdxs, totalVerts, numU, numT } = 
                generateGridMesh(GRID_U, GRID_T, GRID_SPACING);
            const chains = CHAIN_PATTERNS.nearSeam(numT);
            
            applyChainDisplacement(resultData, combinedVerts, numU, numT, chains, 6);

            const params: SubdivisionParams = {
                combinedIdxs,
                resultData,
                combinedVerts,
                outerIdxCount: combinedIdxs.length,
                outerGridVertexCount: totalVerts,
                constraintEdgeSet: new Set(),
                outerW: numU,
                outerH: numT,
                chains,
            };

            const result = await subdivideLongEdges(params, makeFlatEvaluator(MESH_WIDTH, MESH_DEPTH));
            
            expect(result.splitCount).toBeGreaterThan(0);
        });
    });

    describe('Low-poly Sparse Patterns (low_poly_facet)', () => {
        it('detects single isolated feature', () => {
            const { combinedVerts, totalVerts, numU, numT } = generateGridMesh(GRID_U, GRID_T);
            const chains = CHAIN_PATTERNS.lowPolySparse(numT);
            const gridSpacing = 1 / numU;

            const chainAdjacent = identifyChainAdjacentVertices(
                combinedVerts, totalVerts, chains, gridSpacing, numT
            );

            // Even a single feature should be detected
            expect(chainAdjacent.size).toBeGreaterThan(0);
        });

        it('subdivides edges around isolated feature', async () => {
            const { resultData, combinedVerts, combinedIdxs, totalVerts, numU, numT } = 
                generateGridMesh(GRID_U, GRID_T, GRID_SPACING);
            const chains = CHAIN_PATTERNS.lowPolySparse(numT);
            
            // Large displacement for the single prominent feature
            applyChainDisplacement(resultData, combinedVerts, numU, numT, chains, 12);

            const params: SubdivisionParams = {
                combinedIdxs,
                resultData,
                combinedVerts,
                outerIdxCount: combinedIdxs.length,
                outerGridVertexCount: totalVerts,
                constraintEdgeSet: new Set(),
                outerW: numU,
                outerH: numT,
                chains,
            };

            const result = await subdivideLongEdges(params, makeFlatEvaluator(MESH_WIDTH, MESH_DEPTH));
            
            expect(result.splitCount).toBeGreaterThan(0);
        });
    });
});

describe('Chain Detection Robustness', () => {
    it('handles empty chain array gracefully', () => {
        const { combinedVerts, totalVerts, numU, numT } = generateGridMesh(12, 8);
        const chains: ChainUV[] = [];
        const gridSpacing = 1 / numU;

        const chainAdjacent = identifyChainAdjacentVertices(
            combinedVerts, totalVerts, chains, gridSpacing, numT
        );

        expect(chainAdjacent.size).toBe(0);
    });

    it('handles chains with empty points array', () => {
        const { combinedVerts, totalVerts, numU, numT } = generateGridMesh(12, 8);
        const chains: ChainUV[] = [{ points: [] }];
        const gridSpacing = 1 / numU;

        const chainAdjacent = identifyChainAdjacentVertices(
            combinedVerts, totalVerts, chains, gridSpacing, numT
        );

        expect(chainAdjacent.size).toBe(0);
    });

    it('handles very tight tolerance (small grid spacing)', () => {
        const { combinedVerts, totalVerts, numU, numT } = generateGridMesh(12, 8);
        const chains: ChainUV[] = [{ points: [{ u: 0.5, row: 4 }] }];
        // Very small grid spacing = tight tolerance
        const gridSpacing = 0.001;

        const chainAdjacent = identifyChainAdjacentVertices(
            combinedVerts, totalVerts, chains, gridSpacing, numT
        );

        // Tight tolerance should find very few or zero vertices
        expect(chainAdjacent.size).toBeLessThanOrEqual(1);
    });

    it('handles very loose tolerance (large grid spacing)', () => {
        const { combinedVerts, totalVerts, numU, numT } = generateGridMesh(12, 8);
        const chains: ChainUV[] = [{ points: [{ u: 0.5, row: 4 }] }];
        // Very large grid spacing = loose tolerance
        const gridSpacing = 0.5;

        const chainAdjacent = identifyChainAdjacentVertices(
            combinedVerts, totalVerts, chains, gridSpacing, numT
        );

        // Loose tolerance should find many vertices
        expect(chainAdjacent.size).toBeGreaterThan(1);
    });
});
