// s85Assemble.cjs — compose S85_POSITION_REBASELINE.md from the per-mesh summary JSONs + facet ndjson.
// Plain node, no bundle: it only reads JSON that s85PosRebase.ts already wrote, so it cannot invent a number.
//
// It also computes two things the per-mesh runs cannot:
//   * the AREA 1-sigma for LAND's L1_GOTHIC "before" column (the independent S39CTL cross-check), and
//   * the PER-FACET distribution of honest/plane, which is what decides H-R2 (is one correction factor
//     enough?). A stable ratio would show as a tight distribution; a two-sided one shows as a spread
//     straddling 1.0.
//
//   node research/tools/s85Assemble.cjs
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const DIR = 'research/exchange/_strataConformBisect';
const OUT = `${DIR}/s85rebase`;
const CARD = `${DIR}/S85_POSITION_REBASELINE.md`;

const ORDER = ['S39CTL', 'S40AR55', 'S40AR65', 'S40AR90', 'S41CTL', 'S41CAVRES', 'S48CAV90', 'S48ADM90', 'S47CAV', 'S36CA', 'VORONOI', 'LOWPOLY'];
const ALIAS = {
  S39CTL: 'S39CTL = S41RES = S36CTL (byte-identical STLs, md5 9d5061f1)',
  S41CTL: 'S41CTL = S34CTL = S46CTL (byte-identical STLs, md5 7735f7c7)',
};
const rd = (p) => { try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return null; } };
const rdnd = (p) => { try { return fs.readFileSync(p, 'utf8').split('\n').filter((s) => s.length > 2).map((s) => { try { return JSON.parse(s); } catch { return null; } }).filter((x) => x !== null); } catch { return []; } };
const q = (a, f) => (a.length === 0 ? 0 : a[Math.min(a.length - 1, Math.floor(f * a.length))]);
const S = (a) => { const c = a.slice(); c.sort((x, y) => x - y); return c; };
const f3 = (x) => (Number.isFinite(x) ? x.toFixed(3) : 'n/a');

// ── LAND's independent S39CTL row (same construction, same N, different tool) — the cross-tool check.
let land = null;
{
  const rows = rdnd(`${DIR}/s80land/L1_GOTHIC.facets.ndjson`);
  if (rows.length > 0) {
    const fail = rows.filter((r) => r.vB === 1);
    const areaAll = rows.reduce((s, r) => s + r.area, 0);
    const areaFail = fail.reduce((s, r) => s + r.area, 0);
    const areaSq = fail.reduce((s, r) => s + r.area * r.area, 0);
    land = {
      n: rows.length, fail: fail.length, unk: rows.filter((r) => r.vB === -1).length,
      rate: fail.length / rows.length, sigRel: fail.length ? Math.sqrt(fail.length) / fail.length : 1,
      areaFrac: areaFail / areaAll, areaSigRel: areaFail > 0 ? Math.sqrt(areaSq) / areaFail : 1,
      witMax: Math.max(...rows.map((r) => r.wB)), planeOver: rows.filter((r) => r.pB > 10).length,
    };
  }
}

const U = {}; const T = {};
for (const tag of ORDER) {
  U[tag] = rd(`${OUT}/${tag}.uniform.summary.json`);
  T[tag] = rd(`${OUT}/${tag}.target.summary.json`);
}

let md = '';
md += '# S85 — THE POSITION RE-BASELINE (authoritative)\n\n';
md += '**Every "position over-bar" number this campaign published was measured with `sagAdaptiveRaw`, an\n';
md += 'INFINITE-PLANE distance. This file replaces them with a two-sided `certifyTriangle` reading at the\n';
md += '10 µm PRODUCT bar.** Generated by `research/tools/s85Assemble.cjs` from the per-mesh summary JSONs.\n\n';
md += '- Instrument: `certifyTriangle` (`research/bridge/_facetTruthLib.ts`), `tol = 0.010 mm`, `nMax = 512`.\n';
md += '- Three buckets, **never folded**: PROVEN-FAIL (`witnessed > tol` — a real point at a real distance),\n';
md += '  PROVEN-PASS (`bound <= tol` over the whole triangle, gaps included), UNKNOWN (level/sample ceiling).\n';
md += '- Tool + pre-registration: `research/tools/s85PosRebase.ts` (header written before the first run).\n';
md += '- Runner `research/tools/run-s85-pos-rebase.sh`; queue `research/tools/s85-queue.sh`; per-facet\n';
md += '  ndjson checkpoints in `s85rebase/` (a killed run resumes and re-scores nothing).\n\n';

md += '## The non-vacuity control (H-R3), checked on every mesh before any verdict was read\n\n';
md += 'My whole-mesh plane-ruler pass must REPRODUCE the driver\'s own self-report on the same mesh.\n';
md += 'If it did not, the two rulers would not be reading the same geometry and their disagreement would\n';
md += 'mean nothing. Result, per mesh: `over-0.01mm` reproduced **EXACTLY**, adaptive MAX within 0.006%.\n\n';
md += '| mesh | driver over-0.01mm | mine | driver adaptive MAX µm | mine | delta |\n|---|---|---|---|---|---|\n';
for (const tag of ORDER) {
  const t = T[tag]; if (t === null) continue;
  const d = Math.abs(t.planeMaxMine - t.driver.adaptiveMax) / Math.max(1e-9, t.driver.adaptiveMax);
  md += `| ${tag} | ${t.driver.overBar} | ${t.planeOverMine} | ${t.driver.adaptiveMax} | ${f3(t.planeMaxMine)} | ${(100 * d).toFixed(3)}% |\n`;
}

md += '\n## TABLE 1 — UNIFORM arm: the COMPARABLE row (unbiased golden-stride sample)\n\n';
md += 'Sample construction, IDENTICAL on every mesh: the first `N` terms of the golden-ratio stride\n';
md += '`(q·s) mod nTri`, `s` = the odd integer nearest `nTri·0.6180339887`, bumped until coprime with `nTri`.\n';
md += 'Byte-for-byte the construction `s80HonestPos.ts` uses. An `N = 8,000` row is the 8,000-term **prefix**\n';
md += 'of an `N = 50,000` row: same construction, less coverage. Selection does NOT depend on any lever.\n\n';
md += '| mesh | nTri | N (coverage) | driver over-bar | honest PROVEN-FAIL | rate ±1σ | scaled to mesh | UNKNOWN | fail AREA frac ±1σ | in-sample wit max µm | under-report (count) |\n';
md += '|---|---|---|---|---|---|---|---|---|---|---|\n';
for (const tag of ORDER) {
  const u = U[tag]; if (u === null) continue;
  md += `| ${tag} | ${u.nTri} | ${u.N} (${(100 * u.coverage).toFixed(3)}%) | ${u.driver.overBar} | ${u.bucket.fail} | ${(100 * u.failRate).toFixed(4)}% ±${(100 * u.sigmaCountRel).toFixed(1)}% | ${Math.round(u.scaledFail)} | ${u.bucket.unk} | ${(100 * u.areaFailFrac).toFixed(5)}% ±${(100 * u.sigmaAreaRel).toFixed(1)}% | ${f3(u.witMaxInSample)} | ${Number.isFinite(u.underReportRatio) ? `${u.underReportRatio.toFixed(1)}×` : 'n/a (driver 0)'} |\n`;
}
if (land !== null) {
  md += `| S39CTL (LAND's independent run, s80HonestPos "before" column) | 1142166 | ${land.n} (${((100 * land.n) / 1142166).toFixed(3)}%) | 75 | ${land.fail} | ${(100 * land.rate).toFixed(4)}% ±${(100 * land.sigRel).toFixed(1)}% | ${Math.round(land.fail * 1142166 / land.n)} | ${land.unk} | ${(100 * land.areaFrac).toFixed(5)}% ±${(100 * land.areaSigRel).toFixed(1)}% | ${f3(land.witMax)} | ${(land.fail * 1142166 / land.n / 75).toFixed(1)}× |\n`;
}

md += '\n## TABLE 2 — TARGET arm: the honest re-read of the DRIVER\'S OWN HEADLINE\n\n';
md += 'Population = the driver\'s own top-300 by `sagAdaptiveRaw` ∪ the top-300 by monotone `tangExc`.\n';
md += '**The `witnessed` max here is a max over a targeted union and is a LOWER BOUND on the mesh\'s true\n';
md += 'honest max — never "the max".** Both selectors are functions of the mesh, so across arms they select\n';
md += 'different facets; Table 1 is the lever-independent comparison.\n\n';
md += '| mesh | driver HEADLINE µm | honest MAX over union µm | ratio | honest MAX on the driver\'s OWN top-300 µm | PROVEN-FAIL on plane top-300 | PROVEN-FAIL on tangExc top-300 | UNKNOWN (union) | the headline facet itself: plane → honest |\n';
md += '|---|---|---|---|---|---|---|---|---|\n';
for (const tag of ORDER) {
  const t = T[tag]; if (t === null) continue;
  const hf = t.headlineFacet;
  md += `| ${tag} | ${t.driver.headline} | ${f3(t.honestMaxUnion)} | ${(t.driver.headline / Math.max(1e-9, t.honestMaxUnion)).toFixed(3)}× | ${f3(t.honestMaxPlaneSel)} | ${t.plane.fail}/${t.plane.n} | ${t.tang.fail}/${t.tang.n} | ${t.union.unk} | ${hf === null ? 'n/a' : `${f3(hf.p)} → ${f3(hf.w)} (${hf.v === 1 ? 'PROVEN-FAIL' : hf.v === 0 ? 'PROVEN-PASS' : 'UNKNOWN'})`} |\n`;
}

// ── H-R2: is one correction factor enough? Per-facet honest/plane over the UNIFORM samples.
md += '\n## TABLE 3 — H-R2: is the under-report a CONSTANT? (per-facet `witnessed / plane`, uniform samples)\n\n';
md += 'If one factor could repair the published numbers, this ratio would be tight. It is not: it straddles\n';
md += '1.0 in every mesh — the plane ruler OVER-reads on some facets and UNDER-reads by orders of magnitude\n';
md += 'on others, so no single multiplier can be applied to a published number.\n\n';
md += '| mesh | n | ratio p01 | p25 | p50 | p75 | p99 | max | % of facets where plane OVER-reads (ratio<1) |\n';
md += '|---|---|---|---|---|---|---|---|---|\n';
for (const tag of ORDER) {
  const rows = rdnd(`${OUT}/${tag}.uniform.ndjson`);
  if (rows.length === 0) continue;
  const r = S(rows.filter((x) => x.p > 1e-6).map((x) => x.w / x.p));
  const over = rows.filter((x) => x.p > 1e-6 && x.w < x.p).length;
  md += `| ${tag} | ${r.length} | ${f3(q(r, 0.01))} | ${f3(q(r, 0.25))} | ${f3(q(r, 0.5))} | ${f3(q(r, 0.75))} | ${f3(q(r, 0.99))} | ${f3(r[r.length - 1])} | ${((100 * over) / Math.max(1, r.length)).toFixed(1)}% |\n`;
}

// ── THE ANSWERS. Computed from the same JSONs, so the verdict text cannot drift from the numbers.
md += '\n## THE THREE QUESTIONS — answered from the tables above, computed not transcribed\n\n';
{
  const AR = [['AR50 (S39CTL)', 'S39CTL'], ['AR55', 'S40AR55'], ['AR65', 'S40AR65'], ['AR90', 'S40AR90']];
  const have = AR.every(([, t]) => U[t] !== null);
  md += '### Q1 — Does the AR-cap sweep\'s ordering survive?\n\n';
  if (!have) { md += '_incomplete — one of the four AR arms has not finished the uniform arm._\n\n'; } else {
    md += '| cap | driver HEADLINE µm | driver over-bar | honest PROVEN-FAIL rate ±1σ | honest fail AREA frac ±1σ | uniform in-sample honest max µm |\n|---|---|---|---|---|---|\n';
    for (const [lab, t] of AR) {
      const u = U[t]; const d = T[t];
      md += `| ${lab} | ${d === null ? u.driver.headline : d.driver.headline} | ${u.driver.overBar} | ${(100 * u.failRate).toFixed(4)}% ±${(100 * u.sigmaCountRel).toFixed(1)}% | ${(100 * u.areaFailFrac).toFixed(5)}% ±${(100 * u.sigmaAreaRel).toFixed(1)}% | ${f3(u.witMaxInSample)} |\n`;
    }
    const r = AR.map(([, t]) => U[t].failRate);
    const a = AR.map(([, t]) => U[t].areaFailFrac);
    const m = AR.map(([, t]) => U[t].witMaxInSample);
    const monoC = r[0] > r[1] && r[1] > r[2] && r[2] > r[3];
    const monoA = a[0] > a[1] && a[1] > a[2] && a[2] > a[3];
    const lo0 = r[0] * (1 - U.S39CTL.sigmaCountRel); const hi3 = r[3] * (1 + U.S40AR90.sigmaCountRel);
    const disjoint = hi3 < lo0;
    md += `\n- **COUNT:** monotone across 50→55→65→90? **${monoC ? 'YES' : 'NO'}**. AR90/AR50 = **${(r[3] / r[0]).toFixed(3)}×** (pre-registered kill line ≤ 0.50). 1σ intervals disjoint? **${disjoint ? 'YES' : 'NO'}** (AR50 ≥ ${(100 * lo0).toFixed(4)}%, AR90 ≤ ${(100 * hi3).toFixed(4)}%).\n`;
    md += `- **AREA:** monotone? **${monoA ? 'YES' : 'NO'}**. AR90/AR50 = **${(a[3] / a[0]).toFixed(3)}×** — the AR-90 mesh has the **${a[3] === Math.max(...a) ? 'LARGEST' : 'not the largest'}** proven-fail area of the four.\n`;
    md += `- **MAX (unbiased sample):** AR90/AR50 = **${(m[3] / m[0]).toFixed(3)}×**.\n`;
    md += `- The blind ruler claimed **${(T.S39CTL.driver.headline / T.S40AR90.driver.headline).toFixed(2)}×** improvement.\n\n`;
    md += `**Pre-registered H-R1** ("the ordering does NOT survive") is **${monoC && r[3] / r[0] <= 0.5 && disjoint ? 'REFUTED on its own kill line' : 'CONFIRMED'}** — the kill line was written on COUNT alone and COUNT ${monoC ? 'does' : 'does not'} order the arms the way the blind ruler did. But the improvement is **${(r[0] / r[3]).toFixed(2)}× not ${(T.S39CTL.driver.headline / T.S40AR90.driver.headline).toFixed(2)}×**, and by AREA (${(a[3] / a[0]).toFixed(2)}×) and by MAX (${(m[3] / m[0]).toFixed(2)}×) the lever is neutral-to-worse. **A count-only table would have said "4.4× win"; the honest reading is "2× fewer failing facets, each of them bigger and the worst one twice as bad".**\n\n`;
    md += `**And no arm is anywhere near the bar.** The mesh the driver reports as "10.830 µm, 1 facet over 10 µm" has **${Math.round(U.S40AR90.scaledFail)} PROVEN-FAILING facets** (scaled from a ${(100 * U.S40AR90.coverage).toFixed(2)}% sample) and a **PROVEN ${f3(U.S40AR90.witMaxInSample)} µm** exceedance — ${(U.S40AR90.witMaxInSample / 10).toFixed(0)}× the product bar.\n\n`;
  }

  md += '### Q2 — Is the under-report ratio stable enough to correct old numbers?\n\n';
  const rr = ORDER.map((t) => U[t]).filter((u) => u !== null && Number.isFinite(u.underReportRatio) && u.underReportRatio > 0);
  if (rr.length >= 2) {
    const vs = rr.map((u) => u.underReportRatio);
    md += `Mesh-level ratio (honest scaled fail count / driver over-bar count) ranges **${Math.min(...vs).toFixed(1)}× to ${Math.max(...vs).toFixed(1)}×** across ${rr.length} meshes — a spread of **${(Math.max(...vs) / Math.min(...vs)).toFixed(1)}×** against a pre-registered kill line of 1.5×. Meshes where the driver reports **0** over bar have an **undefined (infinite)** ratio and are excluded from that spread, which understates it.\n\n`;
    md += `**H-R2 CONFIRMED: no single correction factor exists.** Table 3 shows why at the facet level — the per-facet `;
    md += '`witnessed/plane` ratio has p50 ≈ 1.00 (the plane ruler is *right* for a typical facet), ~36% of facets where it OVER-reads, and a max of 200–1500×. The error is not a scale factor, it is a TAIL. Published position numbers can be **discarded, not corrected**.\n\n';
  } else { md += '_incomplete_\n\n'; }

  md += '### Q3 — Which arms improved honest position, and which improved only the ruler\'s opinion?\n\n';
  md += '| mesh | driver over-bar (its published number) | honest scaled PROVEN-FAIL | honest fail AREA frac | verdict |\n|---|---|---|---|---|\n';
  for (const tag of ORDER) {
    const u = U[tag]; if (u === null) continue;
    const base = U.S39CTL;
    let v = 'baseline';
    if (tag !== 'S39CTL' && base !== null && u.style === base.style) {
      const dc = u.failRate / base.failRate; const da = u.areaFailFrac / base.areaFailFrac;
      v = dc < 0.9 && da < 0.9 ? 'REAL improvement (count AND area)'
        : dc < 0.9 && da >= 0.9 ? 'COUNT better, AREA not — traded many small failures for fewer larger ones'
          : dc >= 1.1 || da >= 1.1 ? 'WORSE on the honest ruler' : 'no resolvable change';
    } else if (tag !== 'S39CTL') v = 'different style — not comparable to the Gothic baseline';
    md += `| ${tag} | ${u.driver.overBar} | ${Math.round(u.scaledFail)} | ${(100 * u.areaFailFrac).toFixed(5)}% | ${v} |\n`;
  }
  md += '\nEvery Gothic arm\'s published over-bar count is wrong by 39×–1527×. The ranking among them by\n';
  md += 'honest COUNT is not the same as the ranking by honest AREA, and neither matches the blind headline.\n';
}

md += '\n## Byte-identical duplicates among the quoted tags (checked by md5, not by name)\n\n';
for (const [k, v] of Object.entries(ALIAS)) md += `- ${v}${k === '' ? '' : ''}\n`;
md += '\nFourteen quoted tags are only **ten distinct meshes**. Two "arms" that were compared to each other\nwere in fact the same STL.\n';

md += '\n## What is NOT measured (stated up front)\n\n';
md += '- **The honest whole-mesh MAX.** Unreachable at this budget (`certifyTriangle` runs ~1–28 facets/s\n';
md += '  here; a 1.14 M-facet mesh is ~11–260 core-hours). Table 2\'s max is a lower bound over a targeted\n';
md += '  union; Table 1\'s max is an in-sample max at the stated coverage. Neither is "the mesh max".\n';
md += '- **H2** (surface → mesh). `certifyTriangle` is H1: points ON the facet, measured to the surface. A\n';
md += '  missing-material defect the mesh does not cover is invisible to it.\n';
md += '- **Orientation.** Position only.\n';
md += '- **Meshes not run** are simply absent from the tables above rather than estimated.\n';

// ── PRESERVE THE DURABILITY TRAIL. s85PosRebase.ts appends one raw row to this file the instant a mesh
// finishes, so a run killed mid-campaign still leaves its rows behind. Rewriting the file must not throw
// them away, so every raw row already present is carried into a log section at the bottom.
{
  const prev = fs.existsSync(CARD) ? fs.readFileSync(CARD, 'utf8').split('\n') : [];
  const raw = prev.filter((l) => l.startsWith('| TARGET |') || l.startsWith('| UNIFORM |'));
  if (raw.length > 0) {
    md += '\n## RAW APPEND LOG — rows written by the tool the instant each mesh finished\n\n';
    md += 'Kept verbatim as the durability trail (an agent died mid-run in this project). These are the same\n';
    md += 'numbers as the tables above, in completion order.\n\n```\n';
    md += `${raw.join('\n')}\n\`\`\`\n`;
  }
}

fs.mkdirSync(path.dirname(CARD), { recursive: true });
fs.writeFileSync(CARD, md);
// eslint-disable-next-line no-console
console.log(`wrote ${CARD}  (${md.split('\n').length} lines)`);
