"""Inner wall mesh generation for pot geometry.

This module handles the generation of the inner wall rings that form
the interior surface of the pot. It includes:

- Inner wall ring generation with drain clamping
- Face generation for inner wall surface
- Drain hole proximity constraints

The inner wall is generated by offsetting the outer wall inward by the
wall thickness, with special clamping near the drain hole to maintain
structural integrity.
"""

from __future__ import annotations

from typing import Any, Callable

import numpy as np
import numpy.typing as npt
from numpy.typing import NDArray

from ...types import NDArrayFloat


__all__ = [
    "generate_inner_wall",
]


def generate_inner_wall(
    *,
    H: float,
    Rb: float,
    Rt: float,
    expn: float,
    t_wall: float,
    r_drain: float,
    style_opts: dict[str, Any],
    r_outer_fn: Callable[..., Any],
    z_inner: npt.NDArray[np.float64],
    thetas: npt.NDArray[np.float64],
    cos_th: npt.NDArray[np.float64],
    sin_th: npt.NDArray[np.float64],
    n_theta: int,
    verts: list[tuple[float, float, float]],
    base_radius_fn: Callable[..., Any],
    spin_twist_radians_fn: Callable[..., Any],
    call_style_r_outer_fn: Callable[..., Any],
    add_ring_xy_fn: Callable[..., Any],
) -> tuple[npt.NDArray[np.int64], int, int]:
    """Generate inner wall rings with drain hole clamping.
    
    Creates the inner wall of the pot by offsetting the outer wall inward
    by the wall thickness. Applies clamping near the drain hole to prevent
    the inner wall from getting too close to the drain.
    
    Args:
        H: Total height
        Rb: Bottom radius
        Rt: Top radius
        expn: Flare exponent
        t_wall: Wall thickness
        r_drain: Drain hole radius
        style_opts: Style options dictionary
        r_outer_fn: Style function for outer radius
        z_inner: Z-levels for inner wall sampling
        thetas: Theta grid (angular positions)
        cos_th: Cosine of theta grid
        sin_th: Sine of theta grid
        n_theta: Number of theta divisions
        verts: Vertex list to append to
        base_radius_fn: Function to calculate base radius at height
        spin_twist_radians_fn: Function to calculate twist angle
        call_style_r_outer_fn: Function to call style function
        add_ring_xy_fn: Function to add a ring of vertices
        
    Returns:
        Tuple of:
        - inner_idx: Index array for inner wall vertices
        - clamp_count: Number of vertices clamped due to drain proximity
        - total_inner_samples: Total number of inner wall samples
    """
    inner_idx = np.empty((len(z_inner), n_theta), dtype=int)
    clamp_count = 0
    total_inner_samples = len(z_inner) * n_theta
    
    for i, z in enumerate(z_inner):
        twist = spin_twist_radians_fn(z, H, style_opts)
        cTw, sTw = float(np.cos(twist)), float(np.sin(twist))
        r0 = base_radius_fn(z, H, Rb, Rt, expn, style_opts)
        _opts = dict(style_opts)
        _opts.setdefault("_pf_rb", Rb)
        _opts.setdefault("_pf_rt", Rt)
        _opts.setdefault("_pf_expn", expn)
        # Parity with outer/preview: sample style at raw theta; apply twist only in placement
        # Normalize via the typed wrapper to avoid float/NDArray typing ambiguity
        r_out_vals = np.asarray(
            call_style_r_outer_fn(r_outer_fn, thetas, z, r0, H, _opts), dtype=float
        )
        r_in_vals = r_out_vals - t_wall
        min_allowed = r_drain + 1.0
        clamped = r_in_vals < min_allowed
        clamp_count += int(np.count_nonzero(clamped))
        r_in_vals[clamped] = min_allowed
        inner_idx[i] = add_ring_xy_fn(
            verts,
            np.asarray(r_in_vals, dtype=float),
            float(z),
            cTw,
            sTw,
            cos_th,
            sin_th,
            n_theta,
        )
    
    return inner_idx, clamp_count, total_inner_samples
