
from typing import Any

def render_export_section(*args: Any, **kwargs: Any) -> None: ...
def render_metrics_section(*args: Any, **kwargs: Any) -> None: ...
def render_performance_section(*args: Any, **kwargs: Any) -> None: ...
def render_preview_section(*args: Any, **kwargs: Any) -> None: ...
def render_profile_section(*args: Any, **kwargs: Any) -> None: ...
def render_sidebar_section(*args: Any, **kwargs: Any) -> None: ...

__all__ = [
    "render_export_section",
    "render_metrics_section",
    "render_performance_section",
    "render_preview_section",
    "render_profile_section",
    "render_sidebar_section",
]
