/**
 * Topology Snapshot Tests
 * 
 * These tests capture the mesh topology (vertex count, triangle count, index structure)
 * generated by meshBuilder for regression testing.
 * 
 * After GPU migration, we can verify the new implementation produces identical topology.
 */

import { describe, it, expect, beforeAll } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import { buildPotMesh, calculateMeshVolume, getMeshBounds } from './meshBuilder';
import { StyleId, DEFAULT_DIMENSIONS, DEFAULT_QUALITY } from './types';

// Styles to test topology for (representative subset)
const TOPOLOGY_TEST_STYLES: StyleId[] = [
    'SuperformulaBlossom',
    'GothicArches',
    'SpiralRidges',
    'CelticKnot',
];

// Fixed test parameters for reproducibility
const TEST_DIMENSIONS = {
    H: 100,
    Rt: 50,
    Rb: 35,
    tWall: 3,
    tBottom: 3,
    rDrain: 8,
    expn: 1.0,
};

const TEST_QUALITY = {
    nTheta: 48, // Lower for faster tests
    nZ: 24,
};

interface TopologySnapshot {
    styleId: StyleId;
    vertexCount: number;
    triangleCount: number;
    indexBufferHash: string;
    volumeMm3: number;
    boundsMin: [number, number, number];
    boundsMax: [number, number, number];
}

interface TopologySnapshotFile {
    generatedAt: string;
    version: string;
    dimensions: typeof TEST_DIMENSIONS;
    quality: typeof TEST_QUALITY;
    snapshots: Record<string, TopologySnapshot>;
}

const SNAPSHOT_PATH = path.join(__dirname, '__fixtures__', 'topologySnapshots.json');

/**
 * Create a deterministic hash of the index buffer
 */
function hashIndexBuffer(indices: Uint32Array): string {
    const buffer = Buffer.from(indices.buffer);
    return crypto.createHash('md5').update(buffer).digest('hex');
}

/**
 * Generate topology snapshot for a style
 */
function generateSnapshot(styleId: StyleId): TopologySnapshot {
    const { mesh } = buildPotMesh(TEST_DIMENSIONS, TEST_QUALITY, styleId, {});
    const volume = calculateMeshVolume(mesh);
    const bounds = getMeshBounds(mesh);

    return {
        styleId,
        vertexCount: mesh.vertexCount,
        triangleCount: mesh.triangleCount,
        indexBufferHash: hashIndexBuffer(mesh.indices),
        volumeMm3: Math.round(volume * 100) / 100, // Round to 2 decimals
        boundsMin: bounds.min,
        boundsMax: bounds.max,
    };
}

describe('Mesh Topology Snapshots', () => {
    describe('Current Topology Verification', () => {
        for (const styleId of TOPOLOGY_TEST_STYLES) {
            it(`${styleId}: should generate valid mesh with consistent topology`, () => {
                const snapshot = generateSnapshot(styleId);

                // Basic validity checks
                expect(snapshot.vertexCount).toBeGreaterThan(0);
                expect(snapshot.triangleCount).toBeGreaterThan(0);
                expect(snapshot.volumeMm3).toBeGreaterThan(0);

                // Reasonable bounds (pot should be roughly centered)
                expect(snapshot.boundsMin[2]).toBeGreaterThanOrEqual(0); // Z starts at 0
                expect(snapshot.boundsMax[2]).toBeLessThanOrEqual(TEST_DIMENSIONS.H * 1.1);
            });
        }
    });

    describe('Snapshot Generation', () => {
        it('should write topology snapshots when UPDATE_GOLDEN is set', () => {
            if (process.env.UPDATE_GOLDEN !== 'true') {
                console.log('Skipping snapshot update. Set UPDATE_GOLDEN=true to regenerate.');
                return;
            }

            const snapshots: Record<string, TopologySnapshot> = {};

            for (const styleId of TOPOLOGY_TEST_STYLES) {
                console.log(`Generating snapshot for ${styleId}...`);
                snapshots[styleId] = generateSnapshot(styleId);
            }

            const snapshotFile: TopologySnapshotFile = {
                generatedAt: new Date().toISOString(),
                version: '1.0.0',
                dimensions: TEST_DIMENSIONS,
                quality: TEST_QUALITY,
                snapshots,
            };

            const fixturesDir = path.dirname(SNAPSHOT_PATH);
            if (!fs.existsSync(fixturesDir)) {
                fs.mkdirSync(fixturesDir, { recursive: true });
            }

            fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(snapshotFile, null, 2));
            console.log(`Topology snapshots written to: ${SNAPSHOT_PATH}`);
        });
    });

    describe('Snapshot Regression', () => {
        let savedSnapshots: TopologySnapshotFile | null = null;

        beforeAll(() => {
            if (fs.existsSync(SNAPSHOT_PATH)) {
                const content = fs.readFileSync(SNAPSHOT_PATH, 'utf-8');
                savedSnapshots = JSON.parse(content) as TopologySnapshotFile;
            }
        });

        for (const styleId of TOPOLOGY_TEST_STYLES) {
            it(`${styleId}: should match saved topology snapshot`, () => {
                if (!savedSnapshots) {
                    console.log('No snapshots file. Run with UPDATE_GOLDEN=true first.');
                    return;
                }

                const saved = savedSnapshots.snapshots[styleId];
                if (!saved) {
                    console.warn(`No saved snapshot for ${styleId}`);
                    return;
                }

                const current = generateSnapshot(styleId);

                // Critical: vertex and triangle counts must match exactly
                expect(current.vertexCount).toBe(saved.vertexCount);
                expect(current.triangleCount).toBe(saved.triangleCount);

                // Index buffer hash must match (same topology)
                expect(current.indexBufferHash).toBe(saved.indexBufferHash);

                // Volume should be very close (within 1%)
                const volumeDiff = Math.abs(current.volumeMm3 - saved.volumeMm3) / saved.volumeMm3;
                expect(volumeDiff).toBeLessThan(0.01);
            });
        }
    });

    describe('Cross-Style Comparison', () => {
        it('should have different topologies for different styles', () => {
            const snapshots = TOPOLOGY_TEST_STYLES.map(generateSnapshot);

            // All should have the same vertex/triangle count (mesh structure is the same)
            // But index hashes may differ if style affects geometry significantly
            const vertexCounts = new Set(snapshots.map(s => s.vertexCount));

            // Typically all styles produce the same mesh structure (just different positions)
            // so this is informational
            console.log(`Unique vertex counts across styles: ${vertexCounts.size}`);
        });
    });
});
