/**
 * OBJ Export - Wavefront OBJ file generation
 *
 * OBJ is a simple text-based format supported by:
 * - Blender, Maya, 3ds Max, Cinema 4D
 * - Most CAD and mesh editing tools
 * - Online 3D viewers
 *
 * File structure (ASCII):
 * - # Comment lines
 * - v x y z (vertices, 1-indexed)
 * - vn nx ny nz (vertex normals, optional)
 * - f v1 v2 v3 or f v1//n1 v2//n2 v3//n3 (faces)
 *
 * Note: OBJ uses 1-based indexing, not 0-based like JavaScript arrays.
 */

import type { MeshData, Vec3 } from '../types';

// ============================================================================
// Types
// ============================================================================

export interface ExportOBJOptions {
  /** Model name (default: 'PotFoundry') */
  name?: string;
  /** Include vertex normals (default: true) */
  includeNormals?: boolean;
  /** Decimal precision for coordinates (default: 6) */
  precision?: number;
  /** Optional creation timestamp. Omitted by default for deterministic exports. */
  createdAt?: string;
  /** Progress callback */
  onProgress?: (progress: number, message: string) => void;
}

// ============================================================================
// Normal Calculation
// ============================================================================

/**
 * Compute face normal from three vertices
 */
function computeNormal(v0: Vec3, v1: Vec3, v2: Vec3): Vec3 {
  // Edge vectors
  const e1: Vec3 = [v1[0] - v0[0], v1[1] - v0[1], v1[2] - v0[2]];
  const e2: Vec3 = [v2[0] - v0[0], v2[1] - v0[1], v2[2] - v0[2]];

  // Cross product
  const n: Vec3 = [
    e1[1] * e2[2] - e1[2] * e2[1],
    e1[2] * e2[0] - e1[0] * e2[2],
    e1[0] * e2[1] - e1[1] * e2[0],
  ];

  // Normalize
  const len = Math.sqrt(n[0] * n[0] + n[1] * n[1] + n[2] * n[2]);
  if (!Number.isFinite(len) || len < 1e-9) {
    return [0, 0, 1];
  }
  return [n[0] / len, n[1] / len, n[2] / len];
}

// ============================================================================
// OBJ Generation
// ============================================================================

/**
 * Generate OBJ file content as string
 *
 * For very large meshes, use generateStreamingOBJ for Blob output.
 *
 * @param mesh - Mesh data to export
 * @param options - Export options
 * @returns OBJ file content as string
 */
function generateOBJString(mesh: MeshData, options: ExportOBJOptions = {}): string {
  const {
    name = 'PotFoundry',
    includeNormals = true,
    precision = 6,
    createdAt,
  } = options;
  const { vertices, indices, vertexCount, triangleCount } = mesh;

  const lines: string[] = [];

  // Header comments
  lines.push(`# Wavefront OBJ - ${name}`);
  lines.push(`# Generated by PotFoundry`);
  if (createdAt) {
    lines.push(`# Created: ${createdAt}`);
  }
  lines.push(`# Vertices: ${vertexCount.toLocaleString()}, Triangles: ${triangleCount.toLocaleString()}`);
  lines.push('');
  lines.push(`o ${name.replace(/\s+/g, '_')}`);
  lines.push('');

  // Vertices (OBJ uses right-handed coordinate system, same as our mesh data)
  for (let i = 0; i < vertexCount; i++) {
    const x = vertices[i * 3];
    const y = vertices[i * 3 + 1];
    const z = vertices[i * 3 + 2];

    // Handle non-finite values
    const vx = Number.isFinite(x) ? x.toFixed(precision) : '0';
    const vy = Number.isFinite(y) ? y.toFixed(precision) : '0';
    const vz = Number.isFinite(z) ? z.toFixed(precision) : '0';

    lines.push(`v ${vx} ${vy} ${vz}`);
  }

  lines.push('');

  // Normals (per-face normals, referenced by face indices)
  if (includeNormals) {
    for (let i = 0; i < triangleCount; i++) {
      const i0 = indices[i * 3];
      const i1 = indices[i * 3 + 1];
      const i2 = indices[i * 3 + 2];

      const v0: Vec3 = [
        vertices[i0 * 3],
        vertices[i0 * 3 + 1],
        vertices[i0 * 3 + 2],
      ];
      const v1: Vec3 = [
        vertices[i1 * 3],
        vertices[i1 * 3 + 1],
        vertices[i1 * 3 + 2],
      ];
      const v2: Vec3 = [
        vertices[i2 * 3],
        vertices[i2 * 3 + 1],
        vertices[i2 * 3 + 2],
      ];

      const n = computeNormal(v0, v1, v2);

      const nx = Number.isFinite(n[0]) ? n[0].toFixed(precision) : '0';
      const ny = Number.isFinite(n[1]) ? n[1].toFixed(precision) : '0';
      const nz = Number.isFinite(n[2]) ? n[2].toFixed(precision) : '1';

      lines.push(`vn ${nx} ${ny} ${nz}`);
    }
    lines.push('');
  }

  // Faces (1-indexed!)
  // OBJ format: f v1/vt1/vn1 v2/vt2/vn2 v3/vt3/vn3
  // We use: f v1//vn1 v2//vn2 v3//vn3 (no texture coords)
  for (let i = 0; i < triangleCount; i++) {
    // Convert from 0-indexed to 1-indexed
    const v1 = indices[i * 3] + 1;
    const v2 = indices[i * 3 + 1] + 1;
    const v3 = indices[i * 3 + 2] + 1;

    if (includeNormals) {
      const n = i + 1; // Normal index (1-indexed, one normal per face)
      lines.push(`f ${v1}//${n} ${v2}//${n} ${v3}//${n}`);
    } else {
      lines.push(`f ${v1} ${v2} ${v3}`);
    }
  }

  return lines.join('\n');
}

/**
 * Generate OBJ as Blob for large meshes using chunked processing
 */
function generateStreamingOBJ(mesh: MeshData, options: ExportOBJOptions = {}): Blob {
  const {
    name = 'PotFoundry',
    includeNormals = true,
    precision = 6,
    createdAt,
  } = options;
  const { vertices, indices, vertexCount, triangleCount } = mesh;

  const chunks: string[] = [];

  // Header
  chunks.push(`# Wavefront OBJ - ${name}\n`);
  chunks.push(`# Generated by PotFoundry\n`);
  if (createdAt) {
    chunks.push(`# Created: ${createdAt}\n`);
  }
  chunks.push(`# Vertices: ${vertexCount.toLocaleString()}, Triangles: ${triangleCount.toLocaleString()}\n`);
  chunks.push('\n');
  chunks.push(`o ${name.replace(/\s+/g, '_')}\n`);
  chunks.push('\n');

  const blobs: Blob[] = [new Blob(chunks, { type: 'text/plain' })];
  chunks.length = 0;

  // Vertices in chunks
  const CHUNK_SIZE = 50000;

  for (let start = 0; start < vertexCount; start += CHUNK_SIZE) {
    let chunk = '';
    const end = Math.min(start + CHUNK_SIZE, vertexCount);

    for (let i = start; i < end; i++) {
      const x = vertices[i * 3];
      const y = vertices[i * 3 + 1];
      const z = vertices[i * 3 + 2];

      const vx = Number.isFinite(x) ? x.toFixed(precision) : '0';
      const vy = Number.isFinite(y) ? y.toFixed(precision) : '0';
      const vz = Number.isFinite(z) ? z.toFixed(precision) : '0';

      chunk += `v ${vx} ${vy} ${vz}\n`;
    }

    blobs.push(new Blob([chunk], { type: 'text/plain' }));
  }

  blobs.push(new Blob(['\n'], { type: 'text/plain' }));

  // Normals in chunks (if requested)
  if (includeNormals) {
    for (let start = 0; start < triangleCount; start += CHUNK_SIZE) {
      let chunk = '';
      const end = Math.min(start + CHUNK_SIZE, triangleCount);

      for (let i = start; i < end; i++) {
        const i0 = indices[i * 3];
        const i1 = indices[i * 3 + 1];
        const i2 = indices[i * 3 + 2];

        const v0: Vec3 = [
          vertices[i0 * 3],
          vertices[i0 * 3 + 1],
          vertices[i0 * 3 + 2],
        ];
        const v1: Vec3 = [
          vertices[i1 * 3],
          vertices[i1 * 3 + 1],
          vertices[i1 * 3 + 2],
        ];
        const v2: Vec3 = [
          vertices[i2 * 3],
          vertices[i2 * 3 + 1],
          vertices[i2 * 3 + 2],
        ];

        const n = computeNormal(v0, v1, v2);

        const nx = Number.isFinite(n[0]) ? n[0].toFixed(precision) : '0';
        const ny = Number.isFinite(n[1]) ? n[1].toFixed(precision) : '0';
        const nz = Number.isFinite(n[2]) ? n[2].toFixed(precision) : '1';

        chunk += `vn ${nx} ${ny} ${nz}\n`;
      }

      blobs.push(new Blob([chunk], { type: 'text/plain' }));
    }

    blobs.push(new Blob(['\n'], { type: 'text/plain' }));
  }

  // Faces in chunks
  for (let start = 0; start < triangleCount; start += CHUNK_SIZE) {
    let chunk = '';
    const end = Math.min(start + CHUNK_SIZE, triangleCount);

    for (let i = start; i < end; i++) {
      const v1 = indices[i * 3] + 1;
      const v2 = indices[i * 3 + 1] + 1;
      const v3 = indices[i * 3 + 2] + 1;

      if (includeNormals) {
        const n = i + 1;
        chunk += `f ${v1}//${n} ${v2}//${n} ${v3}//${n}\n`;
      } else {
        chunk += `f ${v1} ${v2} ${v3}\n`;
      }
    }

    blobs.push(new Blob([chunk], { type: 'text/plain' }));
  }

  console.log(`[ExportOBJ] Generated OBJ in ${blobs.length} chunks`);
  return new Blob(blobs, { type: 'text/plain' });
}

// ============================================================================
// Public API
// ============================================================================

/**
 * Export mesh to OBJ format
 *
 * @param mesh - Mesh data to export
 * @param options - Export options
 * @returns Blob containing the OBJ file
 */
export async function exportToOBJ(
  mesh: MeshData,
  options: ExportOBJOptions = {}
): Promise<Blob> {
  const { onProgress } = options;

  onProgress?.(0, 'Generating OBJ data...');

  // Use streaming for large meshes
  const STREAMING_THRESHOLD = 500_000;
  const useStreaming =
    mesh.vertexCount > STREAMING_THRESHOLD ||
    mesh.triangleCount > STREAMING_THRESHOLD;

  let blob: Blob;

  if (useStreaming) {
    onProgress?.(0.3, 'Streaming large mesh...');
    blob = generateStreamingOBJ(mesh, options);
  } else {
    const content = generateOBJString(mesh, options);
    blob = new Blob([content], { type: 'text/plain' });
  }

  onProgress?.(1.0, 'OBJ export complete');

  console.log(
    `[ExportOBJ] Created OBJ: ${(blob.size / 1024).toFixed(1)}KB ` +
      `(${mesh.triangleCount.toLocaleString()} triangles)`
  );

  return blob;
}

/**
 * Download mesh as OBJ file
 */
export async function downloadOBJ(
  mesh: MeshData,
  filename: string = 'pot.obj',
  options: ExportOBJOptions = {}
): Promise<void> {
  const blob = await exportToOBJ(mesh, {
    ...options,
    name: options.name ?? filename.replace(/\.obj$/i, ''),
  });

  // Create download
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Estimate OBJ file size
 *
 * OBJ files are text-based, so they're larger than binary STL but smaller
 * than ASCII STL due to vertex sharing.
 */
export function estimateOBJSize(
  mesh: { vertexCount: number; triangleCount: number },
  includeNormals: boolean = true
): number {
  // Vertex lines: "v x.xxxxx y.yyyyy z.zzzzz\n" ≈ 35 bytes
  const vertexData = mesh.vertexCount * 35;

  // Normal lines: "vn nx ny nz\n" ≈ 35 bytes per face
  const normalData = includeNormals ? mesh.triangleCount * 35 : 0;

  // Face lines: "f v1//n1 v2//n2 v3//n3\n" ≈ 30-50 bytes depending on indices
  const faceData = mesh.triangleCount * 40;

  // Header overhead
  const headerOverhead = 200;

  return headerOverhead + vertexData + normalData + faceData;
}
