// _pf_relaxLib.ts — DEV-ONLY meshing LAB (research/, never imported by src/).
//
// E-2026-07-05-PERFECT-MESHER-RELAX. CLOSE the Gothic SLIVER gate on the CONFIRMED 4-bay M-square patch
// (0 interior outliers @0.006mm, watertight non-vacuous, but minAngle 0 / pctBelow20 56.2%).
//
// ROOT CAUSE (measured, _pf_msq_diag): 37.6% of <20° facets sit on the LOW-gradU smooth panel at the
// dense↔coarse GRADING-TRANSITION (RED 1→4 preserves parent needle shape) — NOT the apex. The two levers the
// prior refutations point to:
//   (1) SMOOTH GRADING — replace the abrupt dense↔coarse transition by grading the size ratio between neighbours
//       (gradeBeta-limited). Here we do NOT re-seed (the CONFIRMED mesh already holds fidelity); instead the
//       relaxation itself smooths the transition because it moves points toward locally-uniform mm-spacing, which
//       spreads the abrupt pitch jump into a graded ramp. (A pure re-seed arm is a SEPARATE experiment.)
//   (2) SURFACE-PRESERVING LAPLACIAN-UNDER-M relaxation — iterate FREE (non-crest, non-boundary) vertices toward
//       their M-metric-equilateral (area/angle-optimal) position in the mm-scaled (u,t) chart, RE-PROJECT onto the
//       true analytic surface (trivial: any (u,t) lifts on-surface by construction), and REJECT the move if it
//       makes any incident triangle's honest interior deviation exceed tol (the outlier-hold guard — this is why
//       relaxation succeeds where the a-posteriori Lawson FLIPS of E-…-TIERAB-SLIVERS §3b failed: flips reconnect
//       the SAME needle point set and cannot escape it; relaxation MOVES the points).
//
// THE M=g/h² CHART: mesh in (u,t); the mm-scaled chart is (x=u·arcPerU, y=t·H). On the mean surface this chart is
// arc-length-faithful, so a uniform (mm-space) Laplacian IS the metric-equilateral move to first order. On the
// near-vertical near-crest flank (su≫arcPerU) the mm-chart under-states the true 3D stretch — that is EXACTLY where
// the reject-guard fires (a move that flattens a needle there would over-chord the flank), so fidelity is held by
// the honest brute, not by the chart. This is the correct division of labour: Laplacian for quality, brute for
// fidelity.
//
// ISOLATION: NEW file. Imports _pf_perfectMesherLib + _pf_perfectMesherBruteLib + labkit READ-ONLY. No src/ edit.
import cdt2d from 'cdt2d';
import { type AnalyticRadiusFn } from './labkit';
import { type PatchDef, type ProtectedComplex, lift } from './_pf_perfectMesherLib';
import { facetInteriorBrute } from './_pf_perfectMesherBruteLib';

export interface RelaxRuler { nTheta: number; nZ: number; zBandMm: number; refineIters: number; gnScreen: number; preFilter: number; }
export interface RelaxSweepStat {
  sweep: number; nFree: number; nMoved: number; nRejected: number; maxDispMm: number;
  minAngleDeg: number; medianMinAngle: number; pctBelow20: number; ms: number; guardCalls: number;
}
export interface RelaxResult { uv: number[]; tris: number[]; sweeps: number; hist: RelaxSweepStat[]; }

const TAU = 2 * Math.PI;

// ── SMOOTH-GRADED SEED (lever #1) ────────────────────────────────────────────────────────────────────────────
// The M-square mesh slivers because RED 1→4 creates an ABRUPT dense↔coarse transition (a 2:1 pitch jump →
// hanging-node needles that CDT resolves as slivers). A GRADED seed avoids the jump: background pitch ramps SMOOTHLY
// from hMin (near a crest) to hMax (far), size-ratio between neighbours bounded by gradeBeta ⇒ no abrupt transition
// ⇒ no transition-zone needle parents. Then the SAME honest-brute refine holds fidelity on the near-vertical flank.
//
// Sizing field h(u,t) = clamp(hMin + gradeBeta·dist3D_to_nearest_crest, hMin, hMax). A locally-graded point set is
// generated by a size-field-respecting grid walk in the mm-chart (row pitch = local h; within a row, column pitch =
// local h), which yields a smoothly-graded, isotropic (square-cell) background. Crest/junction verts are prepended
// (locked); CDT with the locked constraint edges = no-bridge graded seed.
export function gradedSeed(
  patch: PatchDef, pc: ProtectedComplex, hMin: number, hMax: number, gradeBeta: number,
): { uv: number[]; tris: number[] } {
  const { rA, H, arcPerU, uLo, uHi, tLo, tHi } = patch;
  const uv = pc.uv.slice();
  const cellMm = 0.02;
  const pmap = new Map<number, number>();
  const key = (u: number, t: number): number => Math.round(u * arcPerU / cellMm) * 100000 + Math.round(t * H / cellMm);
  for (let i = 0; i < uv.length / 2; i++) { const k = key(uv[2 * i], uv[2 * i + 1]); if (!pmap.has(k)) pmap.set(k, i); }
  const addPt = (u: number, t: number): void => { const k = key(u, t); if (pmap.has(k)) return; uv.push(u, t); pmap.set(k, uv.length / 2 - 1); };

  // 3D distance from (u,t) to the nearest crest sample (coarse but smooth); crest samples are dense on the complex.
  const cs = pc.crestSamples3D;
  const distToCrest = (u: number, t: number): number => {
    const [x, y, z] = lift(rA, u, t, H); let best = Infinity;
    for (let i = 0; i < cs.length; i++) { const dx = x - cs[i][0], dy = y - cs[i][1], dz = z - cs[i][2]; const d = dx * dx + dy * dy + dz * dz; if (d < best) best = d; }
    return Math.sqrt(best);
  };
  const hAt = (u: number, t: number): number => Math.max(hMin, Math.min(hMax, hMin + gradeBeta * distToCrest(u, t)));

  // graded grid walk: march t in steps of local h (converted to t-units via H), and within each t-row march u in
  // steps of local h (converted to u-units via arcPerU). Row pitch uses the row's min-h so neighbouring rows never
  // jump more than ~gradeBeta·h (bounded ratio). This is O(nRows·nCols) with a nearest-crest scan per point.
  let t = tLo;
  while (t <= tHi + 1e-9) {
    // row pitch = min local h across a coarse u-scan of this row (respect the finest feature in the row)
    let hRow = hMax;
    for (let s = 0; s <= 8; s++) { const uu = uLo + (uHi - uLo) * (s / 8); const h = hAt(uu, t); if (h < hRow) hRow = h; }
    let u = uLo;
    while (u <= uHi + 1e-9) {
      addPt(u, t);
      const hCol = hAt(u, t);
      u += hCol / arcPerU;
    }
    t += hRow / H;
  }
  const nV = uv.length / 2; const pts: [number, number][] = new Array(nV);
  for (let i = 0; i < nV; i++) pts[i] = [uv[2 * i] * arcPerU, uv[2 * i + 1] * H];
  const tri = cdt2d(pts, pc.constraintEdges as [number, number][], { exterior: true }) as number[][];
  const tris: number[] = []; for (const tr of tri) tris.push(tr[0], tr[1], tr[2]);
  return { uv, tris };
}

// per-triangle 3D min-angle (deg); 0 for degenerate.
function triMinAngle(xyz: Float64Array, a: number, b: number, c: number): number {
  const ax = xyz[3 * a], ay = xyz[3 * a + 1], az = xyz[3 * a + 2];
  const bx = xyz[3 * b], by = xyz[3 * b + 1], bz = xyz[3 * b + 2];
  const cx = xyz[3 * c], cy = xyz[3 * c + 1], cz = xyz[3 * c + 2];
  const la = Math.hypot(bx - cx, by - cy, bz - cz), lb = Math.hypot(cx - ax, cy - ay, cz - az), lc = Math.hypot(ax - bx, ay - by, az - bz);
  if (la < 1e-12 || lb < 1e-12 || lc < 1e-12) return 0;
  const A = Math.acos(Math.max(-1, Math.min(1, (lb * lb + lc * lc - la * la) / (2 * lb * lc))));
  const B = Math.acos(Math.max(-1, Math.min(1, (la * la + lc * lc - lb * lb) / (2 * la * lc))));
  const C = Math.PI - A - B;
  return Math.min(A, B, C) * 180 / Math.PI;
}

function qualitySnapshot(xyz: Float64Array, tris: number[]): { minAngleDeg: number; medianMinAngle: number; pctBelow20: number } {
  const nF = tris.length / 3; const arr = new Float64Array(nF);
  let below20 = 0, minA = 180;
  for (let f = 0; f < nF; f++) {
    const m = triMinAngle(xyz, tris[3 * f], tris[3 * f + 1], tris[3 * f + 2]);
    arr[f] = m; if (m < 20) below20++; if (m < minA) minA = m;
  }
  const s = Float64Array.from(arr).sort();
  const med = s.length ? s[Math.floor(s.length / 2)] : 0;
  return { minAngleDeg: +minA.toFixed(3), medianMinAngle: +med.toFixed(2), pctBelow20: +(100 * below20 / Math.max(1, nF)).toFixed(2) };
}

// ── SURFACE-PRESERVING LAPLACIAN-UNDER-M relaxation with an outlier-hold reject guard ─────────────────────────
// FREE vertex = NOT a crest-constraint endpoint AND NOT on the patch (u,t) boundary (welded-edge incidence==1).
// Move each free vertex toward the M-metric-equilateral target = mm-chart neighbour centroid (the chart (u·arcPerU,
// t·H) is arc-length-faithful on the mean surface ⇒ uniform-mm Laplacian ≈ metric-equilateral). Re-project = lift
// (any (u,t) is on-surface). REJECT if any incident facet's honest full-azimuth-brute interior dev > tol.
//
// omega = damping (0.5 conservative); an ANGLE-WEIGHTED (cotangent-free) simple umbrella suffices — we want the
// vertex nearer the centroid of its 1-ring so long needles fatten. Boundary/crest verts are LOCKED (fidelity +
// watertight are held: crest = no-bridge shared edges; boundary = patch seam continuity).
// local min incident angle at vertex v given the current xyz (over v's incident facets).
function localMinAngle(xyz: Float64Array, tris: number[], incFv: number[]): number {
  let m = 180;
  for (const f of incFv) { const a = triMinAngle(xyz, tris[3 * f], tris[3 * f + 1], tris[3 * f + 2]); if (a < m) m = a; }
  return m;
}

export function relaxLaplacianUnderM(
  patch: PatchDef, mesh: { uv: number[]; tris: number[] }, crestVertexSet: Set<number>,
  tol: number, maxSweeps: number, ruler: RelaxRuler,
  onSweep?: (s: RelaxSweepStat) => void,
  opts?: { omega?: number; qualityDirected?: boolean; nCand?: number },
): RelaxResult {
  const { rA, H, arcPerU } = patch;
  const omega = opts?.omega ?? 0.5;
  // QUALITY-DIRECTED (smart-Laplacian): a plain umbrella centroid is a NO-OP on these slivers (measured: pctBelow20
  // 56.2→56.9, minAngle unchanged) because the needles are a CONNECTIVITY imbalance a centroid move cannot reshape.
  // Instead evaluate candidate positions (umbrella centroid + a ring of offsets toward it) and pick the one that
  // MAXIMIZES the local min incident angle, subject to the fidelity reject-guard AND never lowering local min-angle.
  const qualityDirected = opts?.qualityDirected ?? true;
  const nCand = opts?.nCand ?? 8;
  const uv = mesh.uv.slice(); const tris = mesh.tris.slice();
  const nV0 = uv.length / 2;

  // ── 1-ring adjacency (undirected, by INDEX) + incident-facet list ──
  const adj: Set<number>[] = Array.from({ length: nV0 }, () => new Set<number>());
  const incF: number[][] = Array.from({ length: nV0 }, () => []);
  const nF = tris.length / 3;
  for (let f = 0; f < nF; f++) {
    const a = tris[3 * f], b = tris[3 * f + 1], c = tris[3 * f + 2];
    adj[a].add(b); adj[a].add(c); adj[b].add(a); adj[b].add(c); adj[c].add(a); adj[c].add(b);
    incF[a].push(f); incF[b].push(f); incF[c].push(f);
  }

  // ── boundary detection: weld by 3D position (seam u=0/1 collapses), count welded-edge incidence; incidence==1 ⇒
  //    boundary edge ⇒ its endpoints are boundary verts (LOCKED). ──
  const xyz0 = new Float64Array(nV0 * 3);
  for (let i = 0; i < nV0; i++) { const [x, y, z] = lift(rA, uv[2 * i], uv[2 * i + 1], H); xyz0[3 * i] = x; xyz0[3 * i + 1] = y; xyz0[3 * i + 2] = z; }
  const q = 1e4; const canon = new Int32Array(nV0); const wmap = new Map<string, number>();
  for (let i = 0; i < nV0; i++) { const k = `${Math.round(xyz0[3 * i] * q)}_${Math.round(xyz0[3 * i + 1] * q)}_${Math.round(xyz0[3 * i + 2] * q)}`; const h = wmap.get(k); if (h !== undefined) canon[i] = h; else { wmap.set(k, i); canon[i] = i; } }
  const EK = nV0 + 1; const ekey = (a: number, b: number): number => (a < b ? a * EK + b : b * EK + a);
  const ecnt = new Map<number, number>();
  for (let f = 0; f < nF; f++) { const a = canon[tris[3 * f]], b = canon[tris[3 * f + 1]], c = canon[tris[3 * f + 2]]; if (a === b || b === c || a === c) continue; ecnt.set(ekey(a, b), (ecnt.get(ekey(a, b)) ?? 0) + 1); ecnt.set(ekey(b, c), (ecnt.get(ekey(b, c)) ?? 0) + 1); ecnt.set(ekey(c, a), (ecnt.get(ekey(c, a)) ?? 0) + 1); }
  const boundaryV = new Set<number>();
  for (let f = 0; f < nF; f++) {
    const A = tris[3 * f], B = tris[3 * f + 1], C = tris[3 * f + 2]; const a = canon[A], b = canon[B], c = canon[C]; if (a === b || b === c || a === c) continue;
    if ((ecnt.get(ekey(a, b)) ?? 0) === 1) { boundaryV.add(A); boundaryV.add(B); }
    if ((ecnt.get(ekey(b, c)) ?? 0) === 1) { boundaryV.add(B); boundaryV.add(C); }
    if ((ecnt.get(ekey(c, a)) ?? 0) === 1) { boundaryV.add(C); boundaryV.add(A); }
  }
  // welded crest membership: a vertex is crest-locked iff IT or any position-duplicate is in crestVertexSet.
  const crestW = new Set<number>();
  for (const v of crestVertexSet) crestW.add(canon[v] < nV0 ? canon[v] : v);
  const isCrest = (v: number): boolean => crestVertexSet.has(v) || crestW.has(canon[v]);

  const free: number[] = [];
  for (let v = 0; v < nV0; v++) { if (!isCrest(v) && !boundaryV.has(v)) free.push(v); }

  // honest per-facet interior dev under the trusted full-azimuth brute (SAME ruler that held fidelity).
  const facetDev = (xyz: Float64Array, f: number): number => {
    const a = tris[3 * f], b = tris[3 * f + 1], c = tris[3 * f + 2];
    return facetInteriorBrute(rA, H, xyz, uv, a, b, c, ruler).dev;
  };

  const hist: RelaxSweepStat[] = [];
  let sweep = 0;
  // live xyz (kept in sync with uv on accepted moves)
  const xyz = xyz0;

  for (sweep = 1; sweep <= maxSweeps; sweep++) {
    const t0 = Date.now();
    let nMoved = 0, nRejected = 0, maxDisp = 0, guardCalls = 0;
    for (const v of free) {
      const nb = adj[v]; if (nb.size === 0) continue;
      // mm-chart neighbour centroid (seam-consistent u). Reference u = current vertex u.
      const uc0 = uv[2 * v]; let sx = 0, sy = 0; let n = 0;
      for (const w of nb) {
        let uw = uv[2 * w]; while (uw - uc0 > 0.5) uw -= 1; while (uc0 - uw > 0.5) uw += 1;
        sx += uw * arcPerU; sy += uv[2 * w + 1] * H; n++;
      }
      if (n === 0) continue;
      const targX = sx / n, targY = sy / n;
      const curX = uc0 * arcPerU, curY = uv[2 * v + 1] * H;

      const ou = uv[2 * v], ot = uv[2 * v + 1]; const ox = xyz[3 * v], oy = xyz[3 * v + 1], oz = xyz[3 * v + 2];
      const angBefore = qualityDirected ? localMinAngle(xyz, tris, incF[v]) : 0;

      // CANDIDATE positions: fractions along cur→centroid (quality often peaks BEFORE the full centroid on a graded
      // mesh) PLUS a small perpendicular jitter ring at the centroid (escape a needle whose centroid is collinear).
      // Plain mode = single omega-damped centroid step.
      const cands: Array<[number, number]> = [];
      if (qualityDirected) {
        const dirX = targX - curX, dirY = targY - curY;
        const perpX = -dirY, perpY = dirX; const perpN = Math.hypot(perpX, perpY) || 1;
        const step = Math.hypot(dirX, dirY);
        for (const fr of [1.0, 0.75, 0.5, 0.25]) cands.push([curX + fr * dirX, curY + fr * dirY]);
        // perpendicular jitter at the centroid, magnitude ~ half the centroid step (fatten a collinear needle)
        const jr = 0.5 * step;
        for (let k = 0; k < Math.max(0, nCand - 4); k++) {
          const ang = (k / Math.max(1, nCand - 4)) * Math.PI; // 0..π (± handled by both signs below)
          const jx = Math.cos(ang) * (perpX / perpN) * jr, jy = Math.cos(ang) * (perpY / perpN) * jr;
          cands.push([targX + jx, targY + jy]);
          cands.push([targX - jx, targY - jy]);
        }
      } else {
        cands.push([curX + omega * (targX - curX), curY + omega * (targY - curY)]);
      }

      // evaluate candidates: keep the one with the best local min-angle that (a) passes the fidelity reject-guard AND
      // (b) does not lower the local min-angle below angBefore (never make it worse). First accepted-and-improving
      // wins ties toward the centroid (cands ordered centroid-first).
      let bestU = ou, bestT = ot, bestX = ox, bestY = oy, bestZ = oz, bestAng = angBefore, accepted = false;
      for (const [cx, cy] of cands) {
        const cu = cx / arcPerU;
        const ct = Math.max(patch.tLo + 1e-6, Math.min(patch.tHi - 1e-6, cy / H));
        uv[2 * v] = cu; uv[2 * v + 1] = ct;
        const [nx, ny, nz] = lift(rA, cu, ct, H); xyz[3 * v] = nx; xyz[3 * v + 1] = ny; xyz[3 * v + 2] = nz;
        // quality first (cheap): must strictly improve local min-angle to be worth a (costly) fidelity check
        const angAfter = localMinAngle(xyz, tris, incF[v]);
        if (qualityDirected && angAfter <= bestAng + 1e-6) continue;
        // fidelity reject-guard (honest brute) on every incident facet
        let ok = true;
        for (const f of incF[v]) { guardCalls++; if (facetDev(xyz, f) > tol) { ok = false; break; } }
        if (ok) { bestU = cu; bestT = ct; bestX = nx; bestY = ny; bestZ = nz; bestAng = angAfter; accepted = true; if (!qualityDirected) break; }
      }
      // commit best (or revert)
      uv[2 * v] = bestU; uv[2 * v + 1] = bestT; xyz[3 * v] = bestX; xyz[3 * v + 1] = bestY; xyz[3 * v + 2] = bestZ;
      if (accepted) { nMoved++; const d = Math.hypot(bestX - ox, bestY - oy, bestZ - oz); if (d > maxDisp) maxDisp = d; }
      else nRejected++;
    }
    const qs = qualitySnapshot(xyz, tris);
    const stat: RelaxSweepStat = {
      sweep, nFree: free.length, nMoved, nRejected, maxDispMm: +maxDisp.toFixed(4),
      minAngleDeg: qs.minAngleDeg, medianMinAngle: qs.medianMinAngle, pctBelow20: qs.pctBelow20,
      ms: Date.now() - t0, guardCalls,
    };
    hist.push(stat); if (onSweep) onSweep(stat);
    // convergence: no accepted move OR displacement negligible
    if (nMoved === 0 || maxDisp < 1e-4) break;
  }
  void TAU;
  return { uv, tris, sweeps: sweep, hist };
}
