"""Outer wall mesh generation for pot geometry.

This module handles the generation of the outer wall rings that form
the exterior surface of the pot. It includes:

- Style function delegation and wrapping
- Ring vertex generation with twist
- Vectorized outer wall sampling
- Diagnostic information collection

The outer wall is generated by sampling the style function at each
z-level and creating rings of vertices that are then connected with faces.
"""

from __future__ import annotations

import math
from collections.abc import Callable
from typing import Any, cast

import numpy as np
import numpy.typing as npt

from ...types import NDArrayFloat, StyleOpts

__all__ = [
    "add_ring_xy",
    "call_style_r_outer",
    "sample_outer_rings",
    "spin_twist_radians",
]


# Constant for 2*pi
TAU = 2.0 * math.pi


def call_style_r_outer(
    r_outer_fn: Callable[..., Any],
    th_in: NDArrayFloat | float,
    z_in: float,
    r0_in: float | NDArrayFloat,
    H_in: float,
    opts_in: dict,
) -> NDArrayFloat | float:
    """Typed wrapper to call a style's r_outer function with scalar/array inputs.

    Normalizes r0 to float when appropriate and returns either a float or
    NDArray[float] depending on the style function's output.
    
    Args:
        r_outer_fn: Style function to call
        th_in: Theta values (scalar or array)
        z_in: Z height value
        r0_in: Base radius (scalar or array)
        H_in: Total height
        opts_in: Style options dictionary
        
    Returns:
        Radius value(s) from style function

    """
    try:
        if isinstance(r0_in, np.ndarray):
            r0_arg: float | NDArrayFloat = r0_in
        else:
            r0_arg = float(r0_in)
    except Exception:
        r0_arg = float(r0_in)
    res = r_outer_fn(th_in, z_in, r0_arg, H_in, opts_in)
    if isinstance(res, np.ndarray):
        return cast("NDArrayFloat", np.asarray(res, dtype=float))
    return float(res)


def add_ring_xy(
    verts: list[tuple[float, float, float]],
    r_vals: NDArrayFloat,
    z: float,
    cTw: float,
    sTw: float,
    cos_th: NDArrayFloat,
    sin_th: NDArrayFloat,
    n_theta: int,
) -> npt.NDArray[np.int64]:
    """Append a ring of XY vertices (rotated by twist) and return the index row.
    
    Args:
        verts: Vertex list to append to
        r_vals: Radius values for the ring
        z: Z-height of the ring
        cTw: Cosine of twist angle
        sTw: Sine of twist angle
        cos_th: Cosine of theta grid
        sin_th: Sine of theta grid
        n_theta: Number of theta divisions
        
    Returns:
        Array of vertex indices for this ring

    """
    cx: NDArrayFloat = cos_th * cTw - sin_th * sTw
    sy: NDArrayFloat = sin_th * cTw + cos_th * sTw
    xs: list[float] = (r_vals * cx).tolist()
    ys: list[float] = (r_vals * sy).tolist()
    start_index: int = len(verts)
    from itertools import repeat as _repeat

    verts.extend(zip(xs, ys, _repeat(float(z), n_theta)))
    return np.arange(start_index, start_index + n_theta, dtype=int)


def spin_twist_radians(z: float | npt.NDArray[np.float64], H: float, opts: StyleOpts | dict[str, Any]) -> float | npt.NDArray[np.float64]:
    """Smooth twist angle (in radians) applied to theta at height z.
    
    Calculates the twist angle for the pot at a given height based on
    style options for spin/twist.
    
    Args:
        z: Current height position
        H: Total height
        opts: Style options dictionary with:
            - spin_turns: total revolutions from base to rim (default 0.0)
            - spin_phase_deg: constant offset in degrees (default 0.0)
            - spin_curve_exp: easing exponent for twist vs height (default 1.0)
            
    Returns:
        Twist angle in radians

    """
    if H <= 0:
        return 0.0 if np.isscalar(z) else np.zeros_like(np.asarray(z, dtype=float))
    # Accept canonical aliases if present
    # TypedDict.get is treated as returning `object` by the type checker; cast
    # to the expected primitive types so mypy accepts the float/int conversions.
    turns = float(
        cast("float", opts.get("spin_turns", opts.get("twist_total_turns", 0.0))),
    )
    phase_deg = float(
        cast("float", opts.get("spin_phase_deg", opts.get("twist_start_angle_deg", 0.0))),
    )
    curve = float(
        cast("float", opts.get("spin_curve_exp", opts.get("twist_ease_exponent", 1.0))),
    )
    curve = max(0.1, curve)
    if turns == 0.0 and phase_deg == 0.0:
        return 0.0 if np.isscalar(z) else np.zeros_like(np.asarray(z, dtype=float))

    # Vectorized path: accept array-like z values and return matching array shape
    z_arr = np.asarray(z, dtype=float)
    t = np.clip(z_arr / float(H), 0.0, 1.0)
    # Compute twist: phase + turns*TAU * t**curve
    phase_rad = float(phase_deg) * np.pi / 180.0
    twist_vals = phase_rad + (float(turns) * TAU) * (t ** float(curve))
    # Return scalar for scalar input, array otherwise
    if np.isscalar(z):
        return float(twist_vals)
    return twist_vals


def sample_outer_rings(
    *,
    H: float,
    Rb: float,
    Rt: float,
    expn: float,
    style_opts: dict[str, Any],
    r_outer_fn: Callable[..., Any],
    z_outer: npt.NDArray[np.float64],
    thetas: npt.NDArray[np.float64],
    cos_th: npt.NDArray[np.float64],
    sin_th: npt.NDArray[np.float64],
    n_theta: int,
    verts: list[tuple[float, float, float]],
    base_radius_fn: Callable[..., Any],
) -> tuple[
    npt.NDArray[np.int64],
    list[np.ndarray],
    float | None,
    float | None,
    list[np.ndarray],
    list[np.ndarray],
    int,
    int,
    list[NDArrayFloat],
]:
    """Vectorized sampling of outer rings; appends vertices and returns indices and diagnostics.
    
    Generates the outer wall of the pot by sampling the style function at each
    z-level and creating rings of vertices with applied twist.
    
    Args:
        H: Total height
        Rb: Bottom radius
        Rt: Top radius
        expn: Flare exponent
        style_opts: Style options dictionary
        r_outer_fn: Style function for outer radius
        z_outer: Z-levels for outer wall sampling
        thetas: Theta grid (angular positions)
        cos_th: Cosine of theta grid
        sin_th: Sine of theta grid
        n_theta: Number of theta divisions
        verts: Vertex list to append to
        base_radius_fn: Function to calculate base radius at height
        
    Returns:
        Tuple of:
        - outer_idx: Index array for outer wall vertices
        - r_outer_samples_list: List of radius samples per ring
        - est_top_od: Estimated top outer diameter
        - est_bottom_od: Estimated bottom outer diameter
        - cx_rows_list: Cosine rotation values per ring
        - sy_rows_list: Sine rotation values per ring
        - dbg_outward_picks: Debug counter for outward samples
        - dbg_total_picks: Debug counter for total samples
        - dbg_samples_collected: Debug samples from style

    """
    outer_idx = np.empty((len(z_outer), n_theta), dtype=int)
    r_outer_samples_list: list[np.ndarray] = []
    est_top_od: float | None = None
    est_bottom_od: float | None = None
    dbg_seam = (
        bool(style_opts.get("lp_debug_seam", False))
        if isinstance(style_opts, dict)
        else False
    )
    dbg_outward_picks = 0
    dbg_total_picks = 0
    dbg_samples_collected: list[NDArrayFloat] = []
    cx_rows_list: list[np.ndarray] = []
    sy_rows_list: list[np.ndarray] = []

    for i, z in enumerate(z_outer):
        twist = spin_twist_radians(float(z), H, style_opts)
        cTw, sTw = float(np.cos(twist)), float(np.sin(twist))
        r0 = base_radius_fn(float(z), H, Rb, Rt, expn, style_opts)
        _opts = dict(style_opts)
        _opts.setdefault("_pf_rb", Rb)
        _opts.setdefault("_pf_rt", Rt)
        _opts.setdefault("_pf_expn", expn)
        r_out_raw = call_style_r_outer(r_outer_fn, thetas, float(z), r0, H, _opts)
        r_vals = np.asarray(r_out_raw, dtype=float)
        cx_ring = cos_th * cTw - sin_th * sTw
        sy_ring = sin_th * cTw + cos_th * sTw
        dbg_sample_from_style = _opts.pop("_lp_debug_sample", None)
        if dbg_seam and dbg_sample_from_style is not None:
            dbg_samples_collected.append(dbg_sample_from_style)
        if dbg_seam:
            tiers = int(_opts.get("lp_tiers", 1))
            if tiers > 1:
                t = float(z) / H if H > 0 else 0.0
                tier_pos = t * tiers
                k = int(np.floor(tier_pos))
                eps_z = max(1e-6, 0.002 * H)
                z_bot = (k / tiers) * H
                z_top = ((k + 1) / tiers) * H
                near_seam = (abs(float(z) - z_bot) < eps_z) or (
                    abs(float(z) - z_top) < eps_z
                )
                if near_seam:
                    dbg_total_picks += int(r_vals.size)
                    dbg_outward_picks += int(
                        np.count_nonzero(r_vals > float(r0) + 1e-9),
                    )
        outer_idx[i] = add_ring_xy(
            verts, r_vals, float(z), cTw, sTw, cos_th, sin_th, n_theta,
        )
        cx_rows_list.append(np.asarray(cx_ring, dtype=float))
        sy_rows_list.append(np.asarray(sy_ring, dtype=float))
        r_outer_samples_list.append(r_vals)
        max_r = float(np.max(r_vals)) if r_vals.size else 0.0
        if i == 0:
            est_bottom_od = 2.0 * max_r
        if i == (len(z_outer) - 1):
            est_top_od = 2.0 * max_r

    return (
        outer_idx,
        r_outer_samples_list,
        est_top_od,
        est_bottom_od,
        cx_rows_list,
        sy_rows_list,
        dbg_outward_picks,
        dbg_total_picks,
        dbg_samples_collected,
    )
