// importance_map.wgsl
// GPU Compute for Pre-computing Importance Map for Adaptive Triangulation
//
// This shader samples the style displacement across a grid and computes
// importance based on local curvature (second derivative) and feature proximity.
// The CPU uses this map to generate points proportional to importance.
//
// MUST BE CONCATENATED with common.wgsl and styles.wgsl which provide:
// - TAU constant
// - r_base(t), style_radius() / style functions (they USE getf/style_param we define here)

// ============================================================================
// Bindings (importance map specific)
// ============================================================================

struct ImportanceUniforms {
    chunk0: vec4<f32>, // x:H, y:Rt, z:Rb, w:tWall
    chunk1: vec4<f32>, // x:tBottom, y:rDrain, z:expn, w:styleId
    chunk2: vec4<f32>, // x:spinTurns, y:spinPhase, z:spinCurve, w:reserved
    chunk3: vec4<f32>, // x:gridSize, y:reserved, z:reserved, w:reserved
}

@group(0) @binding(0) var<uniform> imp_uniforms: ImportanceUniforms;
@group(0) @binding(1) var<storage, read> style_params: array<f32>;
@group(0) @binding(2) var<storage, read_write> importance_output: array<f32>;
@group(0) @binding(3) var<storage, read> imp_feature_segments: array<f32>;
@group(0) @binding(4) var<storage, read> imp_grid_offsets: array<u32>;

const IMP_GRID_BINS: u32 = 64u;

// ============================================================================
// Uniform Accessors (required by styles.wgsl functions)
// ============================================================================

fn getf(idx: u32) -> f32 {
    switch idx {
        case 0u: { return imp_uniforms.chunk0.x; }  // H
        case 1u: { return imp_uniforms.chunk0.y; }  // Rt
        case 2u: { return imp_uniforms.chunk0.z; }  // Rb
        case 3u: { return imp_uniforms.chunk1.z; }  // expn
        case 4u: { return imp_uniforms.chunk2.x; }  // spinTurns
        case 5u: { return imp_uniforms.chunk2.y; }  // spinPhase
        case 6u: { return imp_uniforms.chunk2.z; }  // spinCurve
        case 8u: { return 5.0; }   // m_base default
        case 9u: { return 5.0; }   // m_top default
        case 10u: { return 1.0; }  // n1
        case 11u: { return 1.0; }  // n2
        case 12u: { return 1.0; }  // n3
        case 14u: { return 0.0; }  // bellAmp
        case 15u: { return 0.5; }  // bellCenter
        case 72u: { return 0.22; } // bellWidth
        default: { return 0.0; }
    }
}

fn style_param(idx: u32) -> f32 {
    if (idx >= arrayLength(&style_params)) { return 0.0; }
    return style_params[idx];
}

fn style_params_active() -> bool {
    return arrayLength(&style_params) > 0u;
}

fn get_imp_styleId() -> i32 {
    return i32(imp_uniforms.chunk1.w);
}

fn get_imp_gridSize() -> u32 {
    return u32(imp_uniforms.chunk3.x);
}

// ============================================================================
// Style Displacement Sampling (uses style_radius from concatenated styles.wgsl)
// ============================================================================

// Measure style displacement by comparing styled radius to base radius
fn sample_style_displacement(theta: f32, t: f32) -> f32 {
    let r0 = r_base(t);
    // Use style_radius which is dynamically generated by the dispatch code
    let r_styled = style_radius(get_imp_styleId(), theta, t, r0);
    return r_styled - r0; // Displacement from base
}


// ============================================================================
// Curvature Computation
// ============================================================================

fn compute_curvature(u: f32, t: f32) -> f32 {
    // Sample displacement at this point and neighbors
    let theta = u * TAU;
    let eps_u = 0.01;
    let eps_t = 0.01;
    
    let c = sample_style_displacement(theta, t);
    
    // Second derivative in u direction (theta)
    let up = sample_style_displacement(theta + eps_u * TAU, t);
    let um = sample_style_displacement(theta - eps_u * TAU, t);
    let curv_u = abs(up - 2.0 * c + um) / (eps_u * eps_u);
    
    // Second derivative in t direction
    let tp = sample_style_displacement(theta, min(1.0, t + eps_t));
    let tm = sample_style_displacement(theta, max(0.0, t - eps_t));
    let curv_t = abs(tp - 2.0 * c + tm) / (eps_t * eps_t);
    
    // Combined curvature (max of both directions)
    return max(curv_u, curv_t);
}

// ============================================================================
// Feature Proximity
// ============================================================================

struct Segment {
    p1: vec2<f32>,
    p2: vec2<f32>,
}

fn get_imp_segment(idx: u32) -> Segment {
    let base = idx * 4u;
    return Segment(
        vec2<f32>(imp_feature_segments[base], imp_feature_segments[base+1u]),
        vec2<f32>(imp_feature_segments[base+2u], imp_feature_segments[base+3u])
    );
}

fn closest_point_segment(p: vec2<f32>, s: Segment) -> vec2<f32> {
    let ba = s.p2 - s.p1;
    let pa = p - s.p1;
    let dot_ba = dot(ba, ba);
    if (dot_ba < 0.000001) { return s.p1; }
    let h = clamp(dot(pa, ba) / dot_ba, 0.0, 1.0);
    return s.p1 + ba * h;
}

fn compute_feature_proximity(u: f32, t: f32) -> f32 {
    if (arrayLength(&imp_feature_segments) == 0u) { return 0.0; }
    
    let uv = vec2<f32>(u, t);
    
    // Bin lookup for efficient segment search
    let bin_idx = u32(floor(u * f32(IMP_GRID_BINS))) % IMP_GRID_BINS;
    let seg_start = imp_grid_offsets[bin_idx];
    let seg_end = imp_grid_offsets[bin_idx + 1u];
    
    var min_dist_sq = 100.0;
    
    for (var i = seg_start; i < seg_end; i++) {
        let seg = get_imp_segment(i);
        let closest = closest_point_segment(uv, seg);
        let dist_sq = dot(uv - closest, uv - closest);
        min_dist_sq = min(min_dist_sq, dist_sq);
    }
    
    // Convert distance to importance: high when close, low when far
    // Threshold: 0.02 (2% of domain) = 1.0 importance
    let dist = sqrt(min_dist_sq);
    let proximity = max(0.0, 1.0 - dist / 0.05);
    
    return proximity;
}

// ============================================================================
// Main Entry Point
// ============================================================================

@compute @workgroup_size(8, 8, 1)
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {
    let gridSize = get_imp_gridSize();
    
    if (gid.x >= gridSize || gid.y >= gridSize) { return; }
    
    // Compute UV coordinates for this cell center
    let u = (f32(gid.x) + 0.5) / f32(gridSize);
    let t = (f32(gid.y) + 0.5) / f32(gridSize);
    
    // Compute importance from curvature
    let curvature = compute_curvature(u, t);
    
    // Compute importance from feature proximity
    let feature_imp = compute_feature_proximity(u, t);
    
    // Combine: max of curvature-based and feature-based importance
    // Normalize curvature to [0, 1] range (scale factor may need tuning)
    let curv_normalized = min(1.0, curvature / 10.0);
    let importance = max(curv_normalized, feature_imp);
    
    // Write to output
    let idx = gid.y * gridSize + gid.x;
    importance_output[idx] = clamp(importance, 0.0, 1.0);
}
